feat: implements failover logic to relay.org
WalletConnect/WalletConnectKotlinV2 pull request #1002
Opened 2023-07-11 11:01 UTC by jakubuid

2023-07-11 11:13 UTC, Elyniss requested changes

2023-07-11 11:13 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +        val jwt = wcKoinApp.koin.get<GenerateJwtStoreClientIdUseCase>().invoke(SERVER_URL)
```suggestion
        val jwt = get<GenerateJwtStoreClientIdUseCase>().invoke(SERVER_URL)
```

2023-07-11 11:13 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +            .appendQueryParameter("ua", wcKoinApp.koin.get(named(AndroidCommonDITags.USER_AGENT)))
```suggestion
            .appendQueryParameter("ua", get(named(AndroidCommonDITags.USER_AGENT)))
```

2023-07-11 11:13 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +        val jwt = wcKoinApp.koin.get<GenerateJwtStoreClientIdUseCase>().invoke(SERVER_URL)
We mustn't use global wcKoinApp. It most definitely will break Instrumented tests

2023-07-11 11:15 UTC, jakubuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +        val jwt = wcKoinApp.koin.get<GenerateJwtStoreClientIdUseCase>().invoke(SERVER_URL)
Good catch - some leftovers from testing different approaches

2023-07-11 11:25 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/relay/NetworkClientTimeout.kt
> -        private const val MIN_TIMEOUT_LIMIT_AS_MILLIS = 5_000L
Why is this necessary? This was added by a contributor and possibly could break their production

2023-07-11 12:03 UTC, kacperoak commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +                    wasFailOvered = true
This flag stays true forever?

2023-07-11 16:45 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +            .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
double check to see if these logs are still sent to Logcat in a release build. We should not be logging network traffic outside of debug

2023-07-11 17:06 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +            } catch (e: Exception) {
what kind of exception is expected to be thrown? We should more specific about when we want to use the fail-over url instead defaulting to the failover in case of an error

2023-07-12 08:35 UTC, jakubuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/relay/NetworkClientTimeout.kt
> -        private const val MIN_TIMEOUT_LIMIT_AS_MILLIS = 5_000L
It's necessary because 5s timeout is to short for the failover logic to be executed without unnecessary additional tries

2023-07-12 08:43 UTC, jakubuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +                    wasFailOvered = true
Not forever - the init value is false. It's set to true only if the failover logic happens. It's not set back to false because Scarlet instance is a singleton so we cannot re-init it with different url it means that whenever the connection is restarted we need to intercept and replace the failing url with the new one to reduce initialization latency.

2023-07-12 08:44 UTC, jakubuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +            .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
Yeah I agree - overlooked this when cleaning up before creating a PR
I'm gonna add logic to keep this interceptor for debug builds - it's helpful to see what's going on in the network while debugging

2023-07-12 08:45 UTC, jakubuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +            } catch (e: Exception) {
I was not able to get consistency in one error - I can add the set of errors that occurs

2023-07-13 10:39 UTC, jakubuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/relay/NetworkClientTimeout.kt
> -        private const val MIN_TIMEOUT_LIMIT_AS_MILLIS = 5_000L
The solution work fine with 5s timeout as well, so there's no need to increase it

2023-07-13 11:19 UTC, Elyniss requested changes

2023-07-13 15:13 UTC, Elyniss approved these changes

2023-07-13 15:23 UTC, TalhaAli00 approved these changes

2023-07-13 15:39 UTC, merged