Migrate Push SDK to use-cases
WalletConnect/WalletConnectKotlinV2 pull request #1046
Opened 2023-07-25 05:15 UTC by TalhaAli00

2023-07-26 07:45 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/di/PushEngineModule.kt
>  internal fun walletEngineModule() = module {
Do we still need separation between wallet and dapp in Push? The DapClient has been removed right?

2023-07-26 07:47 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/di/PushEngineModule.kt
> +private fun callModule() = module {
What's callModule? It's hard to understand from the name itself

2023-07-26 07:50 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/ApproveUseCase.kt
> +internal class ApproveUseCase(
Let's think about more contextual naming. `ApproveUseCase` doesn't say anything about what this class does. What is being approved? For a dev that doesn't have a Push/Notify context, it's not obvious. I expect that name gives me general understanding of the class responsibility.

2023-07-26 07:52 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DecryptMessageUseCase.kt
> +            // How to look in JsonRpcHistory for dupes without Rpc ID
Should it be marked as a TODO?

2023-07-26 07:53 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DecryptMessageUseCase.kt
> +            val pushMessageEngineDO = PushParams.MessageParams::class.safeCast(pushMessage)?.toEngineDO() ?: return@supervisorScope onFailure(IllegalArgumentException("Unable to deserialize message")
`pushMessageEngineDO`: Should we use `EngineDO` objects in UseCases?

2023-07-26 07:54 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DecryptMessageUseCase.kt
> +            val pushMessageEngineDO = PushParams.MessageParams::class.safeCast(pushMessage)?.toEngineDO() ?: return@supervisorScope onFailure(IllegalArgumentException("Unable to deserialize message")
Let's also add a more detailed error message: "Unable to deserialize push message"

2023-07-26 07:56 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DeleteSubscriptionUseCase.kt
> +        val deleteParams = PushParams.DeleteParams(6000, "User Disconnected")
Seems that `6000, "User Disconnected"` is hard-coded for this case. Let's default these values or create an Error class for it

2023-07-26 07:57 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DeleteSubscriptionUseCase.kt
> +                    logger.log("Delete sent successfully")
"Delete subscription and Echo unregister sent successfully"

2023-07-26 07:58 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DeleteSubscriptionUseCase.kt
> +        val activeSubscription: EngineDO.Subscription.Active = subscriptionRepository.getActiveSubscriptionByPushTopic(pushTopic) ?: return@supervisorScope onFailure(IllegalStateException("Subscripti
Same Q about EngineDO objects

2023-07-26 08:01 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/GetListOfActiveSubscriptionsUseCase.kt
> +    override suspend fun getListOfActiveSubscriptions(): Map<String, EngineDO.Subscription.Active> =
Same Q about EngineDO

2023-07-26 08:01 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/RejectUseCase.kt
> +internal class RejectUseCase(
Same Q about UseCase name

2023-07-26 08:02 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +internal class SubscribeUseCase(
Same Q

2023-07-26 08:05 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +                // Response topic is derived from the sha256 hash of symmetric key S
This is just my thing.  I prefer having comments like this because no one is going to update them when the flow changes so they could be outdated easily. IMO code explains the key derivation flow by itself - if we need a reference for better understanding tho, I'd add a comment to the top of this file that points to the specs repo

2023-07-26 08:07 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +                // Wallet subscribes to response topic
Code says it already

2023-07-26 08:07 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +        val replacedJwk = jwkPublicKey.replace("-", "+").replace("_", "/")
What's JWK?

2023-07-26 08:08 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/UpdateUseCase.kt
> +internal class UpdateUseCase(
Same

2023-07-26 08:09 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/domain/RegisterIdentityAndReturnDidJwtUseCase.kt
> +internal class RegisterIdentityAndReturnDidJwtUseCase(
👏 for a good name

2023-07-26 08:11 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/requests/OnPushProposeUseCase.kt
> +    // Wallet receives push proposal with public key X on pairing topic
👁️ Code should be self-explanatory - if it's not let's add better names

2023-07-26 08:12 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/requests/OnPushProposeUseCase.kt
> +            logger.error("Cannot insert metadata: ${e.message}")
Only logging? Shouldn't respond with error here?

2023-07-26 08:14 UTC, jakubuid requested changes
- Let's think of better naming for UseCases to be more descriptive
- Let's use code and good naming instead of comments that explain what code should already explain by itself

2023-07-26 11:27 UTC, Elyniss commented on protocol/push/src/main/kotlin/com/walletconnect/push/di/PushEngineModule.kt
> +private fun responseModule() = module {
Love the idea of splitting modules! Could we also move them to different files?

2023-07-26 11:27 UTC, Elyniss commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DeleteSubscriptionUseCase.kt
> +        deleteSubscriptionToPushSubscriptionStore(activeSubscription.account, activeSubscription.pushTopic, onSuccess = {}, onError = {})
Imo, yes

2023-07-26 12:43 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/di/PushEngineModule.kt
>  internal fun walletEngineModule() = module {
the name is fine

2023-07-26 12:43 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/di/PushEngineModule.kt
> +private fun callModule() = module {
talked about structure and names

2023-07-26 12:45 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/ApproveUseCase.kt
> +internal class ApproveUseCase(
renamed

2023-07-28 00:18 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DecryptMessageUseCase.kt
> +            // How to look in JsonRpcHistory for dupes without Rpc ID
done

2023-07-28 04:10 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DeleteSubscriptionUseCase.kt
> +        val deleteParams = PushParams.DeleteParams(6000, "User Disconnected")
replaced

2023-07-28 04:13 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DeleteSubscriptionUseCase.kt
> +                    logger.log("Delete sent successfully")
done

2023-07-28 04:16 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +                // Response topic is derived from the sha256 hash of symmetric key S
added specs to subscribe file

2023-07-28 04:18 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +                // Wallet subscribes to response topic
removed

2023-07-28 04:19 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +        val replacedJwk = jwkPublicKey.replace("-", "+").replace("_", "/")
defined here https://docs.walletconnect.com/2.0/specs/clients/push/push-subscribe#pre-requisites

2023-07-28 04:20 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/UpdateUseCase.kt
> +internal class UpdateUseCase(
renamed

2023-07-28 04:39 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/requests/OnPushProposeUseCase.kt
> +            logger.error("Cannot insert metadata: ${e.message}")
added emission of error

2023-07-28 07:32 UTC, jakubuid commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +        val replacedJwk = jwkPublicKey.replace("-", "+").replace("_", "/")
Cannot find it on this link

2023-07-28 07:34 UTC, jakubuid approved these changes

2023-07-28 09:16 UTC, Elyniss approved these changes

2023-07-28 12:34 UTC, Elyniss approved these changes

2023-07-28 12:56 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/di/PushEngineModule.kt
> +private fun responseModule() = module {
done

2023-07-28 12:57 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/RejectUseCase.kt
> +internal class RejectUseCase(
changed to descriptive name

2023-07-28 12:57 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/SubscribeUseCase.kt
> +internal class SubscribeUseCase(
changed to descriptive name

2023-07-28 12:58 UTC, TalhaAli00 commented on protocol/push/src/main/kotlin/com/walletconnect/push/engine/calls/DecryptMessageUseCase.kt
> +            val pushMessageEngineDO = PushParams.MessageParams::class.safeCast(pushMessage)?.toEngineDO() ?: return@supervisorScope onFailure(IllegalArgumentException("Unable to deserialize message")
added more descriptive error messages

2023-07-28 13:23 UTC, merged