Migrate sign and auth engine into use cases
WalletConnect/WalletConnectKotlinV2 pull request #1094
Opened 2023-08-14 15:50 UTC by jakubuid

2023-08-15 05:40 UTC, TalhaAli00 requested changes

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/requests/OnAuthRequestUseCase.kt
> +    operator fun invoke(wcRequest: WCRequest, authParams: AuthParams.RequestParams) {
```suggestion
    operator suspend fun invoke(wcRequest: WCRequest, authParams: AuthParams.RequestParams) {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/requests/OnAuthRequestUseCase.kt
> +                scope.launch { _events.emit(Events.OnAuthRequest(wcRequest.id, wcRequest.topic.value, authParams.payloadParams, verifyContext)) }
won't need to launch after invoke is a suspend fun

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/requests/OnAuthRequestUseCase.kt
> +            scope.launch { _events.emit(SDKError(e)) }
won't need launch after refactor

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/responses/OnAuthRequestResponseUseCase.kt
> +    operator fun invoke(wcResponse: WCResponse, requestParams: AuthParams.RequestParams) {
```suggestion
    operator suspend fun invoke(wcResponse: WCResponse, requestParams: AuthParams.RequestParams) {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/responses/OnAuthRequestResponseUseCase.kt
> +                    scope.launch { _events.emit(Events.OnAuthResponse(response.id, AuthResponse.Error(response.error.code, response.error.message))) }
remove launch after refactor to suspend

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/responses/OnAuthRequestResponseUseCase.kt
> +                        scope.launch {
remove after refactor

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/responses/OnAuthRequestResponseUseCase.kt
> +                        scope.launch {
same

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/responses/OnAuthRequestResponseUseCase.kt
> +            scope.launch { _events.emit(SDKError(e)) }
same

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/CallModule.kt
> +    single { GetListOfVerifyContextsUseCase(get()) }
let's make the return type the interface instead of concrete class. Also, add named arguments

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +        SignEngine(
add named arugments

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +    single { GetPendingSessionRequests(get(), get()) }
named arguments

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/RequestsModule.kt
> +    single { OnPingUseCase(get()) }
same

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/ResponsesModule.kt
> +    single { OnSessionRequestResponseUseCase() }
same

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +    private val getListOfVerifyContextsUseCase: GetListOfVerifyContextsUseCase,
let's inject the interfaces only instead of concrete classes

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
technically, we could create a separate wallet and dapp engine now since we have use-cases

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +    ) {
```suggestion
    ) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +    fun approve(
```suggestion
    suspend fun approve(
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +            supervisorScope {
remove after refactor

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +            throw InvalidNamespaceException(error.message)
return in onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +        jsonRpcInteractor.respondWithParams(request, approvalParams, irnParams) { error -> throw error }
call onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/DisconnectSessionUseCase.kt
> +    fun disconnect(topic: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit)
```suggestion
    suspend fun disconnect(topic: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit)
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/DisconnectSessionUseCase.kt
> +) : DisconnectSessionUseCaseInterface {
```suggestion
) : DisconnectSessionUseCaseInterface = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/DisconnectSessionUseCase.kt
> +            throw CannotFindSequenceForTopic("$NO_SEQUENCE_FOR_TOPIC_MESSAGE$topic")
return onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/EmitEventUseCase.kt
> +) : EmitEventUseCaseInterface {
```suggestion
) : EmitEventUseCaseInterface = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/EmitEventUseCase.kt
> +            throw UnauthorizedEventException(error.message)
call onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/EmitEventUseCase.kt
> +    fun emit(topic: String, event: EngineDO.Event, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit)
```suggestion
    suspend fun emit(topic: String, event: EngineDO.Event, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit)
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/json_rpc/domain/GetPendingSessionRequestByTopicUseCase.kt
> +    fun getPendingSessionRequests(topic: Topic): List<EngineDO.SessionRequest>
```suggestion
    suspend fun getPendingSessionRequests(topic: Topic): List<EngineDO.SessionRequest>
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/json_rpc/domain/GetPendingSessionRequestByTopicUseCase.kt
> +            .filter { record -> serializer.tryDeserialize<SignRpc.SessionRequest>(record.body) != null }
change .filter to .mapNotNull

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/json_rpc/domain/GetPendingRequestsByTopicUseCase.kt
> +    fun getPendingRequests(topic: Topic): List<PendingRequest<String>>
```suggestion
    suspend fun getPendingRequests(topic: Topic): List<PendingRequest<String>>
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/json_rpc/domain/GetPendingRequestsByTopicUseCase.kt
>              .filter { record -> serializer.tryDeserialize<SignRpc.SessionRequest>(record.body) != null }
change .filter to .mapNotNull

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionUpdateResponseUseCase.kt
> +                    scope.launch {
remove launch after refactor

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionUpdateResponseUseCase.kt
> +                    scope.launch { _events.emit(EngineDO.SessionUpdateNamespacesResponse.Error(response.errorMessage)) }
remove launch after

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionSettleResponseUseCase.kt
> +    operator fun invoke(wcResponse: WCResponse) {
```suggestion
    operator suspend fun invoke(wcResponse: WCResponse) {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionRequestResponseUseCase.kt
> +    operator fun invoke(response: WCResponse, params: SignParams.SessionRequestParams) {
```suggestion
    operator suspend fun invoke(response: WCResponse, params: SignParams.SessionRequestParams) {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionRequestResponseUseCase.kt
> +            scope.launch { _events.emit(EngineDO.SessionPayloadResponse(response.topic.value, params.chainId, method, result)) }
remove launch

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/SessionUpdateUseCase.kt
> +    ) {
```suggestion
    ) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/SessionUpdateUseCase.kt
> +            throw InvalidNamespaceException(error.message)
pass in onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/PairUseCase.kt
> +    fun pair(uri: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit)
```suggestion
    suspend fun pair(uri: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit)
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/GetSessionsUseCase.kt
> +    fun getListOfSettledSessions(): List<EngineDO.Session>
```suggestion
    suspend fun getListOfSettledSessions(): List<EngineDO.Session>
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/GetSessionProposalsUseCase.kt
> +    fun getSessionProposals(): List<EngineDO.SessionProposal>
```suggestion
    suspend fun getSessionProposals(): List<EngineDO.SessionProposal>
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ExtendSessionUsesCase.kt
> +            throw UnauthorizedPeerException(UNAUTHORIZED_EXTEND_MESSAGE)
return in onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/PingUseCase.kt
> +    override fun ping(topic: String, onSuccess: (String) -> Unit, onFailure: (Throwable) -> Unit, timeout: Duration) {
```suggestion
    override fun ping(topic: String, onSuccess: (String) -> Unit, onFailure: (Throwable) -> Unit, timeout: Duration) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/PingUseCase.kt
> +                    scope.launch {
remove launch

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ProposeSessionUseCase.kt
> +    fun proposeSession(
```suggestion
    suspend fun proposeSession(
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RejectSessionUseCase.kt
> +    fun reject(proposerPublicKey: String, reason: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit = {})
```suggestion
    suspend fun reject(proposerPublicKey: String, reason: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit = {})
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RejectSessionUseCase.kt
> +    override fun reject(proposerPublicKey: String, reason: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit) {
```suggestion
    override fun reject(proposerPublicKey: String, reason: String, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RejectSessionUseCase.kt
> +        scope.launch {
remove launch

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +    fun respondSessionRequest(
```suggestion
    suspend fun respondSessionRequest(
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +    ) {
```suggestion
    ) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +            throw CannotFindSequenceForTopic("$NO_SEQUENCE_FOR_TOPIC_MESSAGE$topic")
return onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +                    supervisorScope {
remove after

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +    private fun handleExpiration(jsonRpcResponse: JsonRpcResponse, topic: String) {
```suggestion
    private suspend fun handleExpiration(jsonRpcResponse: JsonRpcResponse, topic: String) {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +                throw InvalidExpiryException()
return onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/SessionRequestUseCase.kt
> +    fun sessionRequest(request: EngineDO.Request, onSuccess: (Long) -> Unit, onFailure: (Throwable) -> Unit)
```suggestion
    suspend fun sessionRequest(request: EngineDO.Request, onSuccess: (Long) -> Unit, onFailure: (Throwable) -> Unit)
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/SessionRequestUseCase.kt
> +    override fun sessionRequest(request: EngineDO.Request, onSuccess: (Long) -> Unit, onFailure: (Throwable) -> Unit) {
```suggestion
    override fun sessionRequest(request: EngineDO.Request, onSuccess: (Long) -> Unit, onFailure: (Throwable) -> Unit) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/SessionRequestUseCase.kt
> +            throw UnauthorizedMethodException(error.message)
return onFailure

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionDeleteUseCase.kt
> +    operator fun invoke(request: WCRequest, params: SignParams.DeleteParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, params: SignParams.DeleteParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionDeleteUseCase.kt
> +            scope.launch { _events.emit(SDKError(e)) }
remove launch after

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionDeleteUseCase.kt
> +            scope.launch { _events.emit(params.toEngineDO(request.topic)) }
remove launch

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionEventUseCase.kt
> +    operator fun invoke(request: WCRequest, params: SignParams.EventParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, params: SignParams.EventParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionExtendUseCase.kt
> +    operator fun invoke(request: WCRequest, requestParams: SignParams.ExtendParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, requestParams: SignParams.ExtendParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionProposeUseCase.kt
> +    operator fun invoke(request: WCRequest, payloadParams: SignParams.SessionProposeParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, payloadParams: SignParams.SessionProposeParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionRequestUseCase.kt
> +    operator fun invoke(request: WCRequest, params: SignParams.SessionRequestParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, params: SignParams.SessionRequestParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionSettleUseCase.kt
> +    operator fun invoke(request: WCRequest, settleParams: SignParams.SessionSettleParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, settleParams: SignParams.SessionSettleParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/requests/OnSessionUpdateUseCase.kt
> +    operator fun invoke(request: WCRequest, params: SignParams.UpdateNamespacesParams) {
```suggestion
    operator suspend fun invoke(request: WCRequest, params: SignParams.UpdateNamespacesParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionProposalResponseUseCase.kt
> +    operator fun invoke(wcResponse: WCResponse, params: SignParams.SessionProposeParams) {
```suggestion
    operator suspend fun invoke(wcResponse: WCResponse, params: SignParams.SessionProposeParams) = supervisorScope {
```

2023-08-15 05:40 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/responses/OnSessionProposalResponseUseCase.kt
> +            scope.launch { _events.emit(SDKError(e)) }
remove launch after refactor

2023-08-16 09:27 UTC, jakubuid commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +    private val onAuthRequestResponseUseCase: OnAuthRequestResponseUseCase,
Also we need stateFlow from these classes for collecting engine events

2023-08-16 13:24 UTC, jakubuid commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/calls/RespondAuthRequestUseCase.kt
> +    override fun respond(respond: Respond, onSuccess: () -> Unit, onFailure: (Throwable) -> Unit) {
Why do we need the whole function body in the supervisorScope scope?

2023-08-16 13:25 UTC, jakubuid commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/calls/RespondAuthRequestUseCase.kt
> +                if (!cacaoVerifier.verify(cacao)) throw InvalidCacaoException
IMO throw is better because we're sure know that the code stops execution

2023-08-16 13:27 UTC, jakubuid commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/calls/RespondAuthRequestUseCase.kt
> +                    supervisorScope {
Check and it's not true. It calls for supervisorScope regardless

2023-08-16 14:49 UTC, jakubuid commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
Technically yes, but I'd rather do it in the one of the following PRs

2023-08-16 14:50 UTC, jakubuid commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +            throw InvalidNamespaceException(error.message)
Same as above

2023-08-17 09:37 UTC, Elyniss commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/CallModule.kt
> +internal fun callsModule() = module {
Nit:File name `CallModule.kt` -> `CallsModule.kt`

2023-08-17 09:44 UTC, Elyniss approved these changes

2023-08-17 09:44 UTC, Elyniss commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +        )
Please add named parameters

2023-08-17 10:18 UTC, jakubuid commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +                    supervisorScope {
cant since its on callback

2023-08-18 17:38 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/client/AuthProtocol.kt
> +            runBlocking {
this doesn't need to be blocking, you can do `scope.launch` instead

2023-08-18 17:39 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/client/AuthProtocol.kt
> +            runBlocking { authEngine.respond(params.toCommon(), { onSuccess(params) }, { error -> onError(Auth.Model.Error(error)) }) }
same comment about `scope.launch`

2023-08-18 17:42 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/calls/RespondAuthRequestUseCase.kt
> +                if (!cacaoVerifier.verify(cacao)) throw InvalidCacaoException
That does make sense. It's a better developer exp if we fail fast

2023-08-18 17:44 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/calls/RespondAuthRequestUseCase.kt
> +        crypto.setKey(symmetricKey, responseTopic.value)
this is a big function. It would be helpful if it can be broken up into private funs. But not a requirement

2023-08-18 17:45 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/calls/SendAuthRequestUseCase.kt
> +        } ?: Ttl(DAY_IN_SECONDS)
similar comment about maybe breaking up into smaller funs

2023-08-18 17:45 UTC, TalhaAli00 commented on protocol/auth/src/main/kotlin/com/walletconnect/auth/use_case/requests/OnAuthRequestUseCase.kt
> +                scope.launch { _events.emit(Events.OnAuthRequest(wcRequest.id, wcRequest.topic.value, authParams.payloadParams, verifyContext)) }
good callout. Nvm then

2023-08-18 17:47 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
use `scope.launch` for any function that has callbacks. We only want to call `runBlocking` for functions that return a value

2023-08-18 17:50 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +        jsonRpcInteractor.respondWithParams(request, approvalParams, irnParams) { error -> throw error }
since this is an async error, I think the onFailure is still valid. Everything before has already executed, there's no point in crashing at this point

2023-08-18 17:53 UTC, TalhaAli00 commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/RespondSessionRequestUseCase.kt
> +                throw InvalidExpiryException()
since this is after we respond, onFailure still makes sense

2023-08-18 17:56 UTC, TalhaAli00 approved these changes

2023-08-19 06:00 UTC, jakubuid commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/ApproveSessionUseCase.kt
> +        jsonRpcInteractor.respondWithParams(request, approvalParams, irnParams) { error -> throw error }
all throws are handled on the protocol level, so there's no crash. when this error occurs, the code should be stopped ASAP so i'm gonna keep throw

2023-08-19 06:02 UTC, jakubuid commented on protocol/sign/src/main/kotlin/com/walletconnect/sign/engine/use_case/calls/PingUseCase.kt
> +                    scope.launch {
it's in callback so scope is needed

2023-08-19 08:33 UTC, merged