Refactored order in connect your wallet screen
WalletConnect/WalletConnectKotlinV2 pull request #1119
Opened 2023-09-01 15:28 UTC by kacperoak

2023-09-01 15:29 UTC, Elyniss requested changes
:)

2023-09-07 09:16 UTC, jakubuid approved these changes

2023-09-08 03:50 UTC, TalhaAli00 commented on product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/domain/RecentWalletsRepository.kt
> +class RecentWalletsRepository(
let's make this internal

2023-09-08 03:50 UTC, TalhaAli00 commented on product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/domain/usecase/GetRecentWalletUseCase.kt
> +class GetRecentWalletUseCase(private val repository: RecentWalletsRepository) {
internal

2023-09-08 03:50 UTC, TalhaAli00 commented on product/web3modal/src/main/kotlin/com/walletconnect/web3/modal/domain/usecase/SaveRecentWalletUseCase.kt
> +class SaveRecentWalletUseCase(
internal

2023-09-08 04:01 UTC, TalhaAli00 approved these changes

2023-09-08 09:42 UTC, merged