[W3W] Add scammers screen
WalletConnect/WalletConnectKotlinV2 pull request #1161
Opened 2023-09-22 07:31 UTC by jakubuid

2023-09-22 10:58 UTC, Elyniss approved these changes

2023-09-22 10:58 UTC, Elyniss commented on sample/wallet/src/main/res/drawable/icon_verified_domain.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
nit: rename to ic_verified_domain

2023-09-22 11:01 UTC, Elyniss commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +}
Didn't see "Known security risk" section

2023-09-22 11:28 UTC, kacperoak requested changes

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +        ScammerScreenRoute(sessionProposalUI, navController, shouldOpenProposalDialog)
if it's something like state of composable, don't call this method route. The route is usually an entry point to the screen that we enter through the navcontroller

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +    composableScope: CoroutineScope,
```suggestion
    coroutineScope: CoroutineScope,
```

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
>      val composableScope = rememberCoroutineScope()
```suggestion
    val coroutineScope = rememberCoroutineScope()
```

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_request/SessionRequestUI.kt
> +        var peerContextUI: PeerContextUI
If you change this to var, compose will not recompose when you change this value

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +    shouldOpenProposalDialog: MutableState<Boolean>
Following to the compose approach, it is better to make stateless components if it is posible. So in this case it would be better if you replaced this value with a callback. Thanks to this, you will also be able to use delegate by in the parent.
In this case, if it is a method of opening a dialog and you don't care about value of state. You should do:
`@Composable
fun ScammerScreenRoute(
    sessionProposalUI: SessionProposalUI,
    navController: NavHostController,
    openDialog: () -> Unit
    ) {}
    `

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +    val shouldOpenProposalDialog = remember { mutableStateOf(false) }
```suggestion
    val shouldOpenProposalDialog by remember { mutableStateOf(false) }
```

explanation below

2023-09-22 11:28 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +        ScammerScreenRoute(sessionProposalUI, navController, shouldOpenProposalDialog)
```suggestion
        ScammerScreenRoute(sessionProposalUI, navController,  { shouldOpenProposalDialog = true })
```
explanation below

2023-09-22 11:32 UTC, kacperoak commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_request/SessionRequestUI.kt
> +        var peerContextUI: PeerContextUI
I see that this is UI, it's not a view state, so I guess it doesn't matter. Maybe it's worth making it a state in the VM then react to peerContext changes?

2023-09-27 03:14 UTC, TalhaAli00 commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_request/SessionRequestRoute.kt
> +            val allowButtonColor = if (sessionRequestUI.peerContextUI.isScam == true) mismatch_color else getValidationColor(sessionRequestUI.peerContextUI.validation)
this type of logic happens quite often, maybe we should extract the logic into a function so that we don't have the same `if () mismatch_color else validationColor` all over the code

2023-09-27 03:14 UTC, TalhaAli00 approved these changes

2023-09-28 09:14 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +}
Can you try with: https://malicious-app-verify-simulation.vercel.app/ ?

2023-09-28 09:21 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_request/SessionRequestUI.kt
> +        var peerContextUI: PeerContextUI
It's val, changed it only for testing purposes

2023-09-28 09:38 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +    shouldOpenProposalDialog: MutableState<Boolean>
Goop point. Added a callback instead of mutable state

2023-09-28 09:39 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_proposal/SessionProposalRoute.kt
> +    val shouldOpenProposalDialog = remember { mutableStateOf(false) }
But had to change to var in order to set this value to true in callback

2023-09-28 12:25 UTC, TalhaAli00 commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_request/SessionRequestRoute.kt
> +            val allowButtonColor = if (sessionRequestUI.peerContextUI.isScam == true) mismatch_color else getValidationColor(sessionRequestUI.peerContextUI.validation)
I count 4. You can do a find of `mismatch_color else getValidation` and see each instance in all of the files

2023-09-28 12:48 UTC, kacperoak approved these changes

2023-09-28 14:48 UTC, Elyniss requested changes
Compared to design colors are off

2023-09-28 16:24 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/dialog_routes/session_request/SessionRequestRoute.kt
> +            val allowButtonColor = if (sessionRequestUI.peerContextUI.isScam == true) mismatch_color else getValidationColor(sessionRequestUI.peerContextUI.validation)
Yeah I see. Changed

2023-09-29 08:25 UTC, Elyniss approved these changes
LGTM

2023-09-29 08:29 UTC, merged