Feature/update wallet sample
WalletConnect/WalletConnectKotlinV2 pull request #120
Opened 2022-04-12 02:47 UTC by TalhaAli00

2022-04-12 10:54 UTC, jakobuid requested changes

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/pairings/ActivePairingsFragment.kt
> +class ActivePairingsFragment: Fragment() {
This one is not used

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/sessions/active/ActiveSessionViewModel.kt
> +            else -> SampleWalletEvents.NoAction
```suggestion
         when (walletEvent) {
            is WalletConnect.Model.DeletedSession.Success, is WalletConnect.Model.SettledSessionResponse -> SampleWalletEvents.UpdateSessions(getLatestActiveSessions())
            else -> SampleWalletEvents.NoAction
        }
```

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/sessions/active/ActiveSessionViewModel.kt
> +    val activeSessionEvents = _activeSessionEvents.receiveAsFlow()
Not used

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/sessions/details/SessionDetailsViewModel.kt
> +        // TODO: Once state sync is complete, replace updating UI from VM with event from WalletDelegate
```suggestion
        // TODO: Once state sync is complete, replace updating UI from VM with event from WalletDelegate - SessionUpdateResponse
```

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/sessions/details/SessionDetailsViewModel.kt
> +            val chains = sessionDetails.listOfChainAccountInfo.flatMap { chainAccountInfo: SessionDetailsUI.Content.ChainAccountInfo ->
chains are not used

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/sessions/details/SessionDetailsViewModel.kt
> +//                    blockchain = WalletConnect.Model.SessionPermissions.Blockchain(chains = chains),
Delete?

2022-04-12 10:54 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/sessions/details/SessionDetailsViewModel.kt
> +        // TODO: Once state sync is complete, replace updating UI from VM with event from WalletDelegate
```suggestion
        // TODO: Once state sync is complete, replace updating UI from VM with event from WalletDelegate - onSessionUpgradeResponse
```

2022-04-12 10:54 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +        // TODO: re-init scope
Why? Can you elaborate?

2022-04-20 05:51 UTC, TalhaAli00 commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/host/proposal/SessionProposalBottomSheet.kt
> +    private var _binding: BottomsheetSessionProposalBinding? = null
replaced binding with ext function

2022-04-20 05:52 UTC, TalhaAli00 commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/host/proposal/SessionProposalBottomSheet.kt
> +    private var _binding: BottomsheetSessionProposalBinding? = null
nice catch

2022-04-20 13:04 UTC, TalhaAli00 commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/accounts/uri/UriBottomSheetFragment.kt
> +class UriBottomSheetFragment : BottomSheetDialogFragment() {
there is no constructor that has a layout for dialog fragment

2022-04-20 13:27 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +        // TODO: re-init scope
With the `WalletConnectClient.shutdown()` method, we close the global SDK scope. This can be called when an activity or fragment is closed. When a developer wants to continue to use the SDK after calling shutdown, nothing will work since the scope was cancelled. We need to re-initialize scope if it has been cancelled so the SDK will continue to work

2022-04-20 13:53 UTC, Elyniss approved these changes

2022-04-20 18:43 UTC, jakobuid commented on wallet/src/main/kotlin/com/walletconnect/wallet/ui/pairings/ActivePairingsFragment.kt
> +class ActivePairingsFragment: Fragment() {
Just don't like leaving not used code. But its not a blocker from my side, we can keep it.

2022-04-20 18:47 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +        // TODO: re-init scope
So should we add it before beta100 to let people use shutdown function properly? Otherwise, if we let them use it without scope re-initialisation we gonna have reports that sdk doesn't work.

Or we could comment out shutdown function from public api unit we have proper scope re-initialisation.

2022-04-20 18:59 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +        // TODO: re-init scope
I think it would be good to remove shutdown until the scope work is done. I'll just make the shutdown function private

2022-04-20 19:06 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +        // TODO: re-init scope
Nice, works for me.

2022-04-21 10:46 UTC, jakobuid approved these changes

2022-04-21 13:37 UTC, merged