[Notify] Add JWT validation
WalletConnect/WalletConnectKotlinV2 pull request #1216
Opened 2023-10-26 14:56 UTC by Elyniss

2023-10-27 10:40 UTC, jakubuid approved these changes

2023-10-31 05:32 UTC, TalhaAli00 requested changes

2023-10-31 05:32 UTC, TalhaAli00 commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/data/jwt/NotifyJwtBase.kt
let's make `ACTION_CLAIM_VALUE` an abstract property, then override it in each child. Then you can extract `throwIfActionIsInvalid` and `throwIfBaseIsInvalid` to JwtBase instead of duplicating the functions in each child Claim class

This will also make sure all children have the exact same behavior

2023-10-31 12:43 UTC, TalhaAli00 approved these changes

2023-11-01 12:39 UTC, Elyniss commented
IT passes locally

2023-11-01 12:39 UTC, merged