[Notify/Wallet Sample] Notify Client Refactor
WalletConnect/WalletConnectKotlinV2 pull request #1280
Opened 2024-01-22 15:28 UTC by Elyniss

Introduces Notify Protocol changes:
	- Adds `sbs` and `mjv` fields in jwt requests and responses as per [specs](https://specs.walletconnect.com/2.0/specs/clients/notify/authentication)
	- Subscribe, update and delete requests now await for response from Notify Server

Introduces improved Notify Client interface:
	- Removes old legacy methods
	- Removes notification deletion
	- Add blocking methods for subscription creation, update and deletion
	- Renames multiple methods and models

Introduces Sample Wallet changes:
	- UI waits for subscribe, update and deletion response before ending loading state
	- Removed option to delete notifications
	- Comply to changed Notify Client interface

2024-01-23 02:40 UTC, TalhaAli00 approved these changes

2024-01-23 10:54 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/client/NotifyInterface.kt
Is it already on prod? Asking because we're changing here user facing models

2024-01-23 11:00 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/data/jwt/watchSubscriptions/WatchSubscriptionsResponseJwtClaim.kt
> +private const val VERSION = "1"
Does it make sense to extract VERSION since it's the same for all other claims?

2024-01-23 11:02 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/calls/DeleteSubscriptionUseCase.kt
> +            withTimeout((2 * THIRTY_SECONDS).toDuration(DurationUnit.SECONDS)) {
`2 * THIRTY_SECONDS`
isn't better to just put `SIXTY_SECONDS`?

2024-01-23 11:10 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/calls/DeleteSubscriptionUseCase.kt
> +                while (result.value == DeleteSubscription.Processing) {
Why do we need this timeout and state?

2024-01-23 11:12 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/calls/SubscribeToDappUseCase.kt
> +                    delay(50)
Same question. Why here delay is 50 and for Delete it's 10?

2024-01-23 11:15 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/calls/UpdateSubscriptionRequestUseCase.kt
> +            withTimeout(( 2 * THIRTY_SECONDS).toDuration(DurationUnit.SECONDS)) {
Same

2024-01-23 11:16 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/domain/SetActiveSubscriptionsUseCase.kt
> +            jsonRpcInteractor.batchSubscribe(subscriptionTopic) { error -> launch { _events.emit(SDKError(error)); cancel() } }
Why do you need 'cancel()`?

2024-01-23 11:17 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/requests/OnNotifyMessageUseCase.kt
> +                jsonRpcInteractor.respondWithParams(request.id, request.topic, messageResponseParams, irnParams) { throw it }
log error please

2024-01-23 11:20 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifyDeleteResponseUseCase.kt
> +        _events.emit(params to resultEvent)
Why do you need to emit when this method returns?

2024-01-23 11:21 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifyDeleteResponseUseCase.kt
> +            DeleteSubscription.Error(e)
Please log every exception in Notify SDK with: `logger.error(exception)`

2024-01-23 11:22 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifySubscribeResponseUseCase.kt
> +        _events.emit(params to resultEvent)
Same q. Emit and return?

2024-01-23 11:24 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/bottomsheet_routes/update_subscription/UpdateSubscriptionViewModel.kt
> +                    is Notify.Result.UpdateSubscription.Error -> onFailure(result.error.throwable)
Can you log error?

2024-01-23 11:24 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/bottomsheet_routes/update_subscription/UpdateSubscriptionViewModel.kt
> +                _state.value = UpdateSubscriptionState.Displaying
Can you log error?

2024-01-23 11:25 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/inbox/InboxViewModel.kt
> +    //    private val _searchText = MutableStateFlow("")
Remove

2024-01-23 11:25 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/composable_routes/inbox/InboxViewModel.kt
> +    // todo change back
?

2024-01-23 11:27 UTC, jakubuid requested changes
Please make sure that all errors from both SDK and samples are logged into MixPanel and Firebase

2024-01-23 17:14 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/data/jwt/watchSubscriptions/WatchSubscriptionsResponseJwtClaim.kt
> +private const val VERSION = "1"
Version is payload specific. This means in future notifySubscribe could be at 4 where notifyDelete could still be at 1

2024-01-23 17:14 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/calls/DeleteSubscriptionUseCase.kt
> +                while (result.value == DeleteSubscription.Processing) {
We have to await response from relay before returning from the function

2024-01-23 17:15 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/calls/SubscribeToDappUseCase.kt
> +                    delay(50)
Nice catch. I will extract it to one variable

2024-01-23 17:15 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/domain/SetActiveSubscriptionsUseCase.kt
> +            jsonRpcInteractor.batchSubscribe(subscriptionTopic) { error -> launch { _events.emit(SDKError(error)); cancel() } }
might have blindly copy pasted. nice catch!

2024-01-23 17:18 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifyDeleteResponseUseCase.kt
> +        _events.emit(params to resultEvent)
I need to listen to those events emittions on DeleteSubscriptionUseCase

2024-01-23 17:18 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifySubscribeResponseUseCase.kt
> +        _events.emit(params to resultEvent)
I'm not sure what do you mean by return here

2024-01-23 17:24 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/common/model/CreateSubscription.kt
> +    object Processing : CreateSubscription()
Function blocks until it's success or error. Not sure how to add processing state with blocking function. We could do that with flows but that would be another redesign

2024-01-23 17:36 UTC, Elyniss commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/client/NotifyInterface.kt
We are not aware of any wallets in prod.

2024-01-25 06:22 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifySubscribeResponseUseCase.kt
> +        _events.emit(params to resultEvent)
I thought that this function returns

2024-01-25 06:23 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/bottomsheet_routes/update_subscription/UpdateSubscriptionViewModel.kt
> +                _state.value = UpdateSubscriptionState.Displaying
?

2024-01-25 06:23 UTC, jakubuid commented on sample/wallet/src/main/kotlin/com/walletconnect/sample/wallet/ui/routes/bottomsheet_routes/update_subscription/UpdateSubscriptionViewModel.kt
> +                    is Notify.Result.UpdateSubscription.Error -> onFailure(result.error.throwable)
?

2024-01-25 06:23 UTC, jakubuid commented on protocol/notify/src/main/kotlin/com/walletconnect/notify/engine/responses/OnNotifyDeleteResponseUseCase.kt
> +            DeleteSubscription.Error(e)
?

2024-01-25 12:34 UTC, jakubuid approved these changes

2024-01-26 16:24 UTC, merged