Feature/namespaces refactor
WalletConnect/WalletConnectKotlinV2 pull request #141
Opened 2022-04-28 11:05 UTC by jakobuid

Session namespace refactor, reference: 
- https://github.com/ChainAgnostic/CAIPs/pull/108
- https://github.com/ChainAgnostic/AMS-CASA-gathering/issues/16

2022-04-28 12:52 UTC, Elyniss commented on samples_common/src/main/kotlin/com/walletconnect/sample_common/Constants.kt
> +const val PROJECT_ID = "2ee94aca5d98e6c05c38bce02bee952a"
I think you forgot to remove it.

2022-04-28 12:52 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/sequence/SessionVO.kt
> +//        }
Why not remove this comment?

2022-04-28 12:52 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/Validator.kt
> +    internal fun isEventListNotEmpty(events: List<String>, onInvalidEvents: (String) -> Unit) {
Those methods are only used in tests. Also, I think we decided that methods and events can be empty inside namespaces.

2022-04-28 12:52 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/Validator.kt
> +    internal fun isChainListNotEmpty(chains: List<String>): Boolean =
Same as methods and events. I think we can get rid of it.

2022-04-28 12:52 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
> +            namespaces = listOf(),
I'm not sure this will work.

2022-05-09 14:15 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/core/model/vo/sequence/SessionVO.kt
> +//        }
removed

2022-05-09 14:18 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
> +            namespaces = listOf(),
this has been replaced with list generated from db

2022-05-10 12:29 UTC, Elyniss requested changes

2022-05-10 12:29 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/Validator.kt
> +        if (!session.isSelfController || !session.namespaces.any { namespace -> namespace.events.contains(eventName) }) {
I think only checking if the event exists in any namespace is not sufficient. We need to check if there exists a namespace that contains the event and chainId

2022-05-10 12:29 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
> +        val insertedPairingId = sessionDaoQueries.lastInsertedRow().executeAsOne()
I can smell very unlikely race conditions if two pairing inserts would happen at the same time. Maybe we should add `@Synchronized` to method?

2022-05-10 12:29 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/storage/sequence/SequenceStorageRepository.kt
> +        val lastInsertedSessionId = sessionDaoQueries.lastInsertedRow().executeAsOne()
I can smell very unlikely race conditions if two session inserts would happen at the same time. Maybe we should add @Synchronized to method?

2022-05-10 12:29 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/MetaDataDao.sq
>  -- TODO: change INSERT OR REPLACE and add logic to retrieve id instead
Any idea what is it?

2022-05-10 12:29 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/MetaDataDao.sq
> +	session_id INTEGER,
Can't it be `NOT NULL` as well?

2022-05-10 12:29 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/NamespaceDao.sq
> +    session_id INTEGER NOT NULL,
How about we add `UNIQUE` constraint?

2022-05-17 03:00 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +            return@validateChainIdAuthorization
this is required by the IDE

2022-05-17 03:01 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +            return@validateMethodAuthorisation
same

2022-05-17 03:01 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
>              return@validateChainIdAuthorization
required by IDE

2022-05-17 03:01 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +            return@validateCAIP2
same

2022-05-17 03:01 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +            return@validateNamespaces
same

2022-05-17 03:01 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +                    return@validateMethodAuthorisation
same

2022-05-17 03:01 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +                    return@validateEventAuthorization
same

2022-05-17 03:02 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/Validator.kt
> +    internal fun isEventListNotEmpty(events: List<String>, onInvalidEvents: (String) -> Unit) {
replaced with new requirements

2022-05-17 03:02 UTC, TalhaAli00 commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/Validator.kt
> +        if (!namespaces.any { namespace -> namespace.methods.contains(method) }) {
updated with the new requirements and validation logic

2022-05-19 16:23 UTC, Elyniss requested changes

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/NamespaceDao.sq
> +    session_id INTEGER UNIQUE NOT NULL,
I don't think session_id can have UNIQUE constraint

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/PairingDao.sq
> +    LEFT JOIN MetaDataDao mdd_peer ON pd.topic = mdd_peer.sequence_topic;
If we decide metadata `sequence_topic` can't be `UNIQUE` we can't join by `topic`

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/PairingDao.sq
> +lastInsertedRow:
This is not used anywhere

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/PairingDao.sq
> +getPairingIdByTopic:
This is not used anywhere

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/SessionDao.sq
> +    LEFT JOIN MetaDataDao peer_mdd ON sd.topic = peer_mdd.sequence_topic AND peer_mdd.type = "PEER";
Since `sequence_topic` has `UNIQUE` constraint I believe only one `LEFT JOIN` will work as intended

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/SessionDao.sq
> +    LEFT JOIN MetaDataDao peer_mdd ON sd.topic = peer_mdd.sequence_topic AND peer_mdd.type = "PEER"
Since `sequence_topic` has `UNIQUE` constraint I believe only one `LEFT JOIN` will work as intended

2022-05-19 16:23 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/engine/domain/EngineInteractor.kt
> +            return@validateSessionRequest
```suggestion
            return
```
And make `Validator.validateSessionRequest` inline

2022-05-19 16:25 UTC, Elyniss commented on walletconnectv2/src/main/sqldelight/com/walletconnect/walletconnectv2/storage/data/dao/NamespaceDao.sq
> +    session_id INTEGER NOT NULL,
Making it `UNIQUE` won't work. There can be multiple namespaces for one session

2022-05-20 10:16 UTC, Elyniss approved these changes

2022-05-20 10:17 UTC, merged