Feature/No network and public API refactor
WalletConnect/WalletConnectKotlinV2 pull request #153
Opened 2022-05-17 14:18 UTC by Elyniss

- Added no network handling
- Refactored error handling of pubic API

2022-05-18 11:03 UTC, jakobuid requested changes

2022-05-18 11:03 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/util/NetworkState.kt
> +package com.walletconnect.walletconnectv2.util
Let's move it to the relayer package

2022-05-18 11:03 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/util/NetworkState.kt
> +        conManager.registerDefaultNetworkCallback(callback)
```suggestion
        (context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager).registerDefaultNetworkCallback(callback)
```

2022-05-18 11:03 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/util/NetworkState.kt
> +        conManager.registerDefaultNetworkCallback(callback)
```suggestion
        (context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager).registerDefaultNetworkCallback(callback)
```

2022-05-18 19:50 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/domain/RelayerInteractor.kt
> +    ) { wws, internet -> wws && internet }
Typo changed.

Regarding two events, upon reading [StateFlow docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/) I'm certain that it will never emit two `false` or `true` states

2022-05-19 09:50 UTC, Elyniss commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +    fun setWalletDelegate(
We decided that using WalletConnectException in onError would require too much work. Left a comment for future and created an issue

2022-05-19 13:49 UTC, jakobuid requested changes
Last comments

2022-05-19 13:49 UTC, jakobuid commented on dapp/src/main/kotlin/com/walletconnect/dapp/domain/DappDelegate.kt
> +        }
I recall we agreed to remove onError callback from setDappDelegate and setWalletDelegate

2022-05-19 13:49 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +    private fun checkEngineInitialization() {
Let's move this private methods to the bottom of the file

2022-05-19 13:49 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +    fun setWalletDelegate(delegate: WalletDelegate, onError: (WalletConnect.Model.Error) -> Unit) {
This should not have onError callback if I remember correctly

2022-05-19 13:49 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/client/WalletConnectClient.kt
> +    fun setDappDelegate(delegate: DappDelegate, onError: (WalletConnect.Model.Error) -> Unit) {
The same

2022-05-19 13:55 UTC, Elyniss commented on dapp/src/main/kotlin/com/walletconnect/dapp/domain/DappDelegate.kt
> +        }
Good catch!

2022-05-20 07:46 UTC, jakobuid approved these changes

2022-05-20 08:03 UTC, merged