moved sign code into separate directory
WalletConnect/WalletConnectKotlinV2 pull request #190
Opened 2022-06-09 04:49 UTC by TalhaAli00

2022-06-13 07:28 UTC, jakobuid reviewed
@TalhaAli00 
Is this PR ready to be reviewed?
I pull changes and:
- Wallet and Dapp sample application class doesn't see `sample_common` module
- there is no chadSDK directory neither signSDK
- walletconnectv2 module should be renamed to sign

2022-06-14 13:38 UTC, Elyniss approved these changes

2022-06-15 06:59 UTC, jakobuid requested changes

2022-06-15 06:59 UTC, jakobuid commented on chatSDK/chat/src/androidTest/java/com/walletconnect/chat/ExampleInstrumentedTest.kt
> +
Let's remove it if not used

2022-06-15 06:59 UTC, jakobuid commented on chatSDK/chat/src/test/java/com/walletconnect/chat/ExampleUnitTest.kt
> +class ExampleUnitTest {
Let's remove this file if not used

2022-06-15 06:59 UTC, jakobuid commented on chatSDK/chatsample/src/androidTest/java/com/walletconnect/chatsample/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
Let's remove this file if not used

2022-06-15 06:59 UTC, jakobuid commented on chatSDK/chatsample/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Let's remove this file if not used

2022-06-15 06:59 UTC, jakobuid commented on chatSDK/chatsample/src/main/res/drawable/ic_launcher_background.xml
> +<?xml version="1.0" encoding="utf-8"?>
Let's remove this file if not used

2022-06-15 06:59 UTC, jakobuid commented on signSDK/sign/build.gradle.kts
>                  from(components.getByName("release"))
I think we don't even need this piece of code since we use Github to release artefacts, let's remove it.

2022-06-15 06:59 UTC, jakobuid commented on README.md
> +[Chat SDK](chatSDK)
Imo it doesn't look nice, there is no any guides about the project structure neither about what are our products. We should include such introduction in here because we left our users in the dark. I believe our goal is not to have main ReadMe looking like in the image below.

<img width="1274" alt="Screenshot 2022-06-15 at 08 57 14" src="https://user-images.githubusercontent.com/23366251/173762641-3481346e-02f1-49ff-b9d9-58c1a2115c92.png">

2022-06-15 07:01 UTC, jakobuid commented
@TalhaAli00 I glanced over but gonna have next round when:
- Conflicts are resolved
- Just to avoid spam in comments, let's remove all android boilerplate code that is not necessarily used like all test files, icons etc.
- Have a look at the ReadMe comment

2022-06-15 13:19 UTC, TalhaAli00 commented on signSDK/sign/build.gradle.kts
>                  from(components.getByName("release"))
this is for internal testing if we want to create an AAR before we actually release. This script would be helpful when we start working on Chat before we release with Jitpack. Maybe we can move this into its own file and apply it where it's needed

2022-06-15 13:24 UTC, TalhaAli00 commented on README.md
> +[Chat SDK](chatSDK)
I agree it does not look great but the idea is to have a table of contents of all of our products. Do we not want anything like that?

2022-06-15 13:45 UTC, jakobuid commented
@TalhaAli00 PR merged

2022-06-15 14:27 UTC, jakobuid approved these changes

2022-06-16 04:40 UTC, TalhaAli00 commented
Closed and started new branch. PR: https://github.com/WalletConnect/WalletConnectKotlinV2/pull/210

2022-06-16 04:40 UTC, closed without merging