Added onError callback to delegates
WalletConnect/WalletConnectKotlinV2 pull request #214
Opened 2022-06-17 05:48 UTC by TalhaAli00

2022-06-17 07:14 UTC, jakobuid requested changes

2022-06-17 07:14 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/engine/model/EngineDO.kt
> +import java.lang.Exception
Not used

2022-06-17 07:14 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/relay/domain/RelayerInteractor.kt
> +    private fun handleError(errorMessage: String) {
Any reason of not emitting internal error on lines 205, 198, 166, 151, 141, 132 and 127?

2022-06-17 12:39 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/relay/domain/RelayerInteractor.kt
> +    private fun handleError(errorMessage: String) {
Good catch on 198 and 205. The rest of the lines are already handled in their respective onFailure callbacks. There's no reason to emit the same error twice. This internal error should be only for things that the developer does not already receive through a normal workflow

2022-06-17 14:23 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/engine/model/EngineDO.kt
> +import java.lang.Exception
removed

2022-06-17 14:24 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/relay/domain/RelayerInteractor.kt
> +    private fun handleError(errorMessage: String) {
added other handleError calls

2022-06-20 09:13 UTC, Elyniss approved these changes

2022-06-20 15:40 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/relay/domain/RelayerInteractor.kt
> +    private fun handleError(errorMessage: String) {
imo, the internal validations should be fast failures. If a validation fails, I don't think a developer should wait to catch the error in the delegate. We're basically doing a catch and if a developer is not looking closely as the `onError` function, then the validation error could be missed.

As for the `respondWithError`, I'm on the fence. Since the SDK automatically responds to the peer with an error, does a developer need to know the peer sent a back request?

2022-06-20 15:40 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/relay/domain/RelayerInteractor.kt
> +    private fun handleError(errorMessage: String) {
@WalletConnect/kotlin-team

2022-06-21 13:54 UTC, Elyniss commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/relay/domain/RelayerInteractor.kt
> +    private fun handleError(errorMessage: String) {
> As for the respondWithError, I'm on the fence. Since the SDK automatically responds to the peer with an error, does a developer need to know the peer sent a back request?

I don't think so

2022-06-21 14:55 UTC, merged