Change waku to iridium
WalletConnect/WalletConnectKotlinV2 pull request #215
Opened 2022-06-17 10:31 UTC by jakobuid

2022-06-17 14:27 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/network/model/RelayDTO.kt
> +            val method: String = "iridium_publish",
make these strings constants that can re-used in Sign and RelayDTO

2022-06-20 09:16 UTC, Elyniss requested changes
Can we extract all those methods to some file?

2022-06-20 11:12 UTC, Elyniss approved these changes

2022-06-20 15:41 UTC, TalhaAli00 approved these changes

2022-06-20 19:37 UTC, merged