Iridium JWT
WalletConnect/WalletConnectKotlinV2 pull request #220
Opened 2022-06-21 03:22 UTC by TalhaAli00

2022-06-21 03:23 UTC, TalhaAli00 reviewed
@WalletConnect/kotlin-team Hey guys, started working on adding the client id. I believe I'm following the JS signing logic correctly, could you take a look and see if there are any issues in the logic? Also, there's a bug with the serializing of the JSON objects right now

2022-06-29 06:56 UTC, jakobuid requested changes

2022-06-29 06:56 UTC, jakobuid commented on signSDK/dapp/src/main/kotlin/com/walletconnect/dapp/DappSampleApplication.kt
> +            nonceServerUrl = "https://$WALLET_CONNECT_PROD_RELAY_URL",
I think we don't have to expose nonce url. Should be enough to handle in internally.

2022-06-29 06:56 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/keystore/KeyChain.kt
> +        val concatKeys = sharedPreferences.getString(tag, null) ?: throw WalletConnectException.InternalError("unable to find keys")
With this change we have to make sure that we handle this exception.

2022-06-29 06:56 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +    }
Is it always false?

2022-06-29 06:56 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +    }
Are we sure it'd never be null?

2022-06-29 06:56 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +        val did = getDIDFromNewKeyPair()
Shouldn't be `did` always the same unless user uninstall app?

2022-06-29 06:56 UTC, jakobuid commented on signSDK/wallet/src/main/kotlin/com/walletconnect/wallet/WalletSampleApplication.kt
> +            nonceServerUrl = "https://$WALLET_CONNECT_PROD_RELAY_URL",
Same

2022-06-29 06:59 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                    if (jwtRepository.jwtExists()) {
I think we don't need that check, we should create a new jwt every-time on new wss connection right?

2022-06-30 07:59 UTC, jakobuid approved these changes
I figure out why we have `WalletConnectException$MissingInternetConnectionException: No connection available`. This is because with current server impl we got the 401 error which cases our wss connection no to be initialised.

2022-06-30 07:59 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                Logger.log("Engine Initialized")
Let's remove this log

2022-06-30 07:59 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyStore.kt
> +    fun checkKeys(tag: String): Boolean
Test fails because KeyChainMock is lacking of checkKeys method

2022-06-30 07:59 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +        val subject = generateNonce()
```suggestion
        val subject = generateSubject()
```

2022-06-30 12:55 UTC, TalhaAli00 commented
> I figure out why we have `WalletConnectException$MissingInternetConnectionException: No connection available`. This is because with current server impl we got the 401 error which cases our wss connection no to be initialised. 

For reference, here is the PR for the server changes
https://github.com/WalletConnect/ts-relay/pull/149/files

2022-06-30 15:06 UTC, Elyniss approved these changes

2022-07-01 14:07 UTC, TalhaAli00 commented on signSDK/dapp/src/main/kotlin/com/walletconnect/dapp/DappSampleApplication.kt
> +            nonceServerUrl = "https://$WALLET_CONNECT_PROD_RELAY_URL",
this has been removed

2022-07-01 14:12 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/keystore/KeyChain.kt
> +        val concatKeys = sharedPreferences.getString(tag, null) ?: throw WalletConnectException.InternalError("unable to find keys")
I agree but I think just putting the throws annotation should be sufficient. Before, we were returning an empty string and were not protecting against it, mostly because the scenario isn't really possible unless there's a device error.

2022-07-01 14:13 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +    }
no longer needed

2022-07-01 14:13 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +        val did = getDIDFromNewKeyPair()
removed

2022-07-01 14:13 UTC, TalhaAli00 commented on signSDK/wallet/src/main/kotlin/com/walletconnect/wallet/WalletSampleApplication.kt
> +            nonceServerUrl = "https://$WALLET_CONNECT_PROD_RELAY_URL",
removed

2022-07-01 14:14 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                    if (jwtRepository.jwtExists()) {
removed

2022-07-01 14:14 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                Logger.log("Engine Initialized")
log was removed by Jakob

2022-07-01 14:14 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyStore.kt
> +    fun checkKeys(tag: String): Boolean
method added

2022-07-01 14:15 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +        val subject = generateNonce()
renamed by Jakob

2022-07-01 14:22 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/repository/JwtRepository.kt
> +    }
removed since it's no longer needed

2022-07-01 14:40 UTC, merged