Feature/envelope types
WalletConnect/WalletConnectKotlinV2 pull request #221
Opened 2022-06-21 11:42 UTC by jakobuid

2022-06-21 15:40 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/core/model/vo/sync/ParticipantsVO.kt
> +package com.walletconnect.sign.core.model.vo.sync
add `@file:JvmSynthetic` at the top of the file. This will help prevent a Java user from being able to use this file

2022-06-21 15:41 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyManagementRepository.kt
> +package com.walletconnect.sign.crypto
JvmSynth annotation

2022-06-21 15:41 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyStore.kt
>  import com.walletconnect.sign.core.model.vo.Key
JvmSynth annotation

2022-06-21 15:42 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/codec/ChaChaPolyCodec.kt
> +package com.walletconnect.sign.crypto.data.codec
JvmSynth annotation

2022-06-21 15:45 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/data/codec/ChaChaPolyCodec.kt
> +    companion object {
you can put `private` a the beginning of the companion object. Then you don't need private on every variable

2022-06-22 11:16 UTC, Elyniss requested changes
Looks good to me. I would only change visibility of `EnvelopeType` to `internal`

2022-06-23 07:06 UTC, Elyniss approved these changes

2022-06-23 07:57 UTC, TalhaAli00 approved these changes

2022-06-23 08:23 UTC, merged