KeyServer API
WalletConnect/WalletConnectKotlinV2 pull request #223
Opened 2022-06-21 17:04 UTC by Elyniss

2022-06-21 17:10 UTC, Elyniss commented on signSDK/samples_common/src/main/kotlin/com/walletconnect/sample_common/Constants.kt
> +const val PROJECT_ID = BuildConfig.PROJECT_ID
I've added ENV VAR:
`export WC_CLOUD_PROJECT_ID=2ee94aca5d98e6c05c38bce02bee952a`

With this we won't have to worry about having it inside the repo.

2022-06-21 18:41 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/di/EngineModule.kt
> +package com.walletconnect.chat.di
add JvmSynth annotation

2022-06-21 18:41 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/di/KeyServerModule.kt
> +package com.walletconnect.chat.di
JvmSynth annotation

2022-06-21 18:42 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/di/KeyServerModule.kt
> +    val TIMEOUT_TIME = 5000L
can we make this private?

2022-06-21 18:43 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/di/KeyServerModule.kt
> +            ResolveAccountUseCase(get())
I think it would be better to create the different UseCases as separate singletons then inject the use case into Interactor

2022-06-21 18:44 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/data/client/KeyServerClient.kt
> +}
any reason why this needs to be an interface? We only have one impl, can't this be a concrete class?

2022-06-21 18:47 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/KeyServerInteractor.kt
> +internal class KeyServerInteractor(
The interactor is just a passthrough class here, I think we can just inject the usecases into the ChatEngine

2022-06-21 18:47 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/RegisterAccountUseCase.kt
> +    operator fun invoke(account: EngineDO.Account): Flow<Result<Unit>> = flow {
does this have to return a flow?

2022-06-21 18:48 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
>  package com.walletconnect.chat.engine.domain
add JvmSynth annotation

2022-06-21 18:48 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/model/KeyServerDTO.kt
> +package com.walletconnect.chat.discovery.keyserver.model
add JvmSynth annotation

2022-06-21 18:48 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/ResolveAccountUseCase.kt
> +package com.walletconnect.chat.discovery.keyserver.domain.use_case
add JvmSynth annotation

2022-06-21 18:48 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/RegisterAccountUseCase.kt
> +package com.walletconnect.chat.discovery.keyserver.domain.use_case
JvmSynth annotation

2022-06-21 18:48 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/data/service/KeyServerService.kt
> +package com.walletconnect.chat.discovery.keyserver.data.service
JvmSynth annotation

2022-06-21 18:49 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/data/client/KeyServerClientImpl.kt
> +package com.walletconnect.chat.discovery.keyserver.data.client
JvmSynth annotation

2022-06-21 18:49 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/data/client/KeyServerClient.kt
> +package com.walletconnect.chat.discovery.keyserver.data.client
JvmSynth annotation

2022-06-21 18:49 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/model/EngineDO.kt
>  package com.walletconnect.chat.engine.model
JvmSynth annotation

2022-06-21 18:49 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/model/EngineMapper.kt
>  package com.walletconnect.chat.engine.model
JvmSynth annotation

2022-06-21 18:53 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/model/EngineMapper.kt
> +// TODO: Organize Mappers - Where should mapping methods between client and engine be (ClientMapper.kt or EngineMapper.kt)?
The pattern we decided on using for the Sign SDK was to only expose an object with the ending `VO` (which means Value Object) between layers (data -> domain). So the repository should convert all DTO objects to a VO object and inside the EngineMapper, you map the VO object to a DO object which is used inside of the Engine.

The benefit is that we can expose only the data we need and remove things like IDs or anything else the DTO will need or DB objects.

2022-06-21 18:58 UTC, TalhaAli00 commented on chatSDK/chatsample/src/main/kotlin/com/walletconnect/chatsample/ui/host/ChatSampleActivity.kt
> +            .launchIn(lifecycleScope)
nice

2022-06-21 18:59 UTC, TalhaAli00 commented on chatSDK/chatsample/src/main/kotlin/com/walletconnect/chatsample/ui/host/ChatSampleViewModel.kt
> +            is Chat.Model.Events.OnRegister -> ChatSampleEvents.OnRegister(wcEvent.publicKey)
are these events only supposed to fire once?

2022-06-22 08:48 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/di/KeyServerModule.kt
> +    val TIMEOUT_TIME = 5000L
This is `fun`. I'm not sure what you mean

2022-06-22 09:01 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/KeyServerInteractor.kt
> +internal class KeyServerInteractor(
Yes, we can. I was just sugarcoating the architecture. My idea was to aggregate all use-cases into one interactor so that engine won't have multiple use-cases in the constructor. 

Also, this class could later be renamed to `DiscoverabilityInteractor` where we could fit use-cases for resolving ens public keys. 

Given that, what do you think? @TalhaAli00

2022-06-22 09:03 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/RegisterAccountUseCase.kt
> +    operator fun invoke(account: EngineDO.Account): Flow<Result<Unit>> = flow {
Nice catch, it was a residue from my tinkering with custom `Result` that supports `Loading` state, but I abandoned the idea. I will remove Flow and stick to Result

2022-06-22 09:14 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/model/EngineMapper.kt
>  package com.walletconnect.chat.engine.model
So to sum up this JvmSynth annotation. We need to add this to every file that has something internal inside it, right?

2022-06-22 09:19 UTC, Elyniss commented on chatSDK/chatsample/build.gradle.kts
> +    implementation("com.andrognito.flashbar:flashbar:1.0.3")
Moved to snackbar

2022-06-22 09:42 UTC, Elyniss commented on chatSDK/chatsample/src/main/kotlin/com/walletconnect/chatsample/ui/host/ChatSampleViewModel.kt
> +            is Chat.Model.Events.OnRegister -> ChatSampleEvents.OnRegister(wcEvent.publicKey)
Yeah, nice catch. I've added a clear cache method to `ChatDelegate`

2022-06-22 10:22 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/model/EngineMapper.kt
> +// TODO: Organize Mappers - Where should mapping methods between client and engine be (ClientMapper.kt or EngineMapper.kt)?
I think I understand it now. Take a look at introduced with new commit VO classes and mappings

2022-06-22 11:38 UTC, jakobuid requested changes

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/di/KeyServerModule.kt
> +    val TIMEOUT_TIME = 5000L
I guess it's about making `TIMEOUT_TIME` private, but it doesn't make sense because it is scoped to module block.

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/KeyServerInteractor.kt
> +internal class KeyServerInteractor(
I like your idea @Elyniss however I'm against doing optimization when it doesn't bring any value to the project architecture.

I'd rather do it when it's really needed, as you said for instance when we'd have to add resolving ens public keys feature.

I think now is just too early.

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/RegisterAccountUseCase.kt
> +
Empty space

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/ResolveAccountUseCase.kt
> +
Empty space

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/use_case/RegisterAccountUseCase.kt
> +    suspend operator fun invoke(account: AccountVO): Result<Unit> = try {
Here inside `AccountVO` you have `account` and `publicKey` but in the `ResolveAccountUseCase` you pass account of type string.

It's a bit confusing because we have two definitions of account then.

One is account address with pubKey, the other is just account address.
Maybe we could just jus AccountVO with optional pubKey?

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
> +                onSuccess = { account -> _events.emit(EngineDO.Events.OnResolve(account.publicKey).toVOOnResolve()) },
Do we really need to emit an event here?
I think if we use the onSuccess callback as you do with error it should be all good. Or even `onResult(Result<OnResolve>)`

This is single http request where success or failure is received almost immediately.

It is done in this way in Sing because we publish a message over wss, where such message has to be handled by the other peer before receiving ack.

What do you think?

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
> +                onSuccess = { _events.emit(EngineDO.Events.OnRegister(publicKey).toVOOnRegister()) },
Same

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chatsample/src/main/AndroidManifest.xml
> +<!--TODO: Remove android:usesCleartextTraffic="true"-->
Why not just remove it? :)

2022-06-22 11:38 UTC, jakobuid commented on chatSDK/chatsample/src/main/AndroidManifest.xml
> +            android:exported="true">
Do we wanna have only portret mode?

2022-06-22 12:01 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +        data class Register(val account: String, val publicKey: String, val private: Boolean? = false) : Params()
This key is always a public key. From what I understood from the specs & discussions, after MVP the `private` flag will tell whether we should register a given account in our KeyServer.

2022-06-22 12:03 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
> +                onSuccess = { account -> _events.emit(EngineDO.Events.OnResolve(account.publicKey).toVOOnResolve()) },
Plus we don't need to scope after we receive a result. So it's better to use supervisorScope and cancel it whenever we success or error.

2022-06-22 12:04 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/copiedFromSign/core/scope/WalletConnectScope.kt
> +package com.walletconnect.chat.copiedFromSign.core.scope
Todo added, however, the idea behind naming module `copiedFromSign` is to indicate exactly what you propose.

2022-06-22 12:19 UTC, Elyniss commented on chatSDK/chatsample/src/main/AndroidManifest.xml
> +<!--TODO: Remove android:usesCleartextTraffic="true"-->
Right now keyserver has no TLS cert

2022-06-22 12:30 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/KeyServerInteractor.kt
> +internal class KeyServerInteractor(
I honestly believe it does bring value right now. 

However, if both of you agree it doesn't bring value I will gladly remove `KeyServerInteractor`

2022-06-22 13:56 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
> +                onSuccess = { account -> _events.emit(EngineDO.Events.OnResolve(account.publicKey).toVOOnResolve()) },
I think Engine should not be aware of any thread switching. If developers want to update an UI on onFailure, it should be in their side to remember about the handling it on the right thread.

It applies for both the onSuccess and the onError.

We shouldn't force any context switching.

2022-06-23 10:34 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/discovery/keyserver/domain/KeyServerInteractor.kt
> +internal class KeyServerInteractor(
Removed it

2022-06-24 11:01 UTC, jakobuid requested changes

2022-06-24 11:01 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyManagementRepository.kt
> +    // Needs to be added with Chat SDK
?

2022-06-24 11:18 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/copiedFromSign/crypto/KeyManagementRepository.kt
> +    //Added with Chat SDK
It was only to explicitly say what was added in Chat SDK. Right now there are two files `KeyManagementRepository.kt` . I just added it to not be confused if whose two files become out of sync later on.

2022-06-24 11:26 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +
I don't like the fact that every Listener has `onSuccess` with a predefined String parameter. How about this solution

```suggestion
    sealed interface Listeners {
      fun onError(error: Model.Error)
      private interface PublicKeyOnSuccess {
        fun onSuccess(publicKey: String)
      } : Listeners
      
      interface Resolve : PublicKeyOnSuccess
      interface Register : PublicKeyOnSuccess
    }

```

2022-06-27 07:11 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +
Yea looks good!

2022-06-27 14:13 UTC, Elyniss commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyManagementRepository.kt
> +    // Needs to be added with Chat SDK
Removed

2022-06-27 14:25 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +            val peerAccount: String,
Good call. Added AccountId value class. Also added `fun isValid()` for SDK consumer to validate correctness

2022-06-29 05:08 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +            val signature: String? = null,
should this be defaulted to null?

2022-06-29 05:09 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +            fun isValid() = AccountIdVO(value).isValid()
instead of wrapping value with `AccountIdVO`, can't you just run the validator logic here? We should try to not expose our internal object like VO classes

2022-06-29 05:47 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/ChatProtocol.kt
>  package com.walletconnect.chat.client
add jvmsynth annotation

2022-06-30 05:05 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/ChatProtocol.kt
> +    override fun register(register: Chat.Params.Register, listener: Chat.Listeners.Register) {
is the reason for changing from lamdas to interfaces for Java support?

2022-06-30 06:05 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/copiedFromSign/crypto/data/keystore/KeyChain.kt
> +        return privateKeyByteArray.bytesToHex() to publicKeyByteArray.bytesToHex()
maybe make the return type `Pair<PrivateKey, PublicKey>` to make sure that we don't mix up the two keys

2022-06-30 06:07 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/copiedFromSign/crypto/data/keystore/KeyChain.kt
> +    override fun getKeys(tag: String): Pair<String, String> {
make sure that the usage of this function is consistent

2022-06-30 06:14 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/domain/Validator.kt
> +package com.walletconnect.chat.engine.domain
jvmSynth annotation

2022-06-30 06:15 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/engine/model/EngineMapper.kt
>  package com.walletconnect.chat.engine.model
correct, any internal class or file that has internal functions. This will prevent the files and classes from being seen when using Java since internal is a Kotlin specific feature

2022-06-30 06:16 UTC, TalhaAli00 approved these changes

2022-06-30 15:23 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/ChatProtocol.kt
> +    override fun register(register: Chat.Params.Register, listener: Chat.Listeners.Register) {
The main reason was that callback should not be handled as the event from our SDK like i.e. sessionPropose.

2022-06-30 15:24 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +            fun isValid() = AccountIdVO(value).isValid()
I think that doing it this way is not exposing the VO class. I didn't want to have multiple definitions of validation for public and internal AccountId value class

2022-06-30 16:03 UTC, merged