Feature/chat json rpc methods
WalletConnect/WalletConnectKotlinV2 pull request #235
Opened 2022-06-30 11:07 UTC by jakobuid

2022-06-30 12:58 UTC, TalhaAli00 reviewed
~~Can you merge in the key server PR? There is overlap in files like build.Gradle and dependencies for example~~

Nvm, I thought there were missing dependencies from another PR

2022-06-30 13:05 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/ChatProtocol.kt
> +                    networkModule(serverUrl, ConnectionType.AUTOMATIC),
Can't we default the connection type parameter to Automatic so we don't have to pass it?

2022-07-01 04:57 UTC, Elyniss requested changes

2022-07-01 04:57 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/mapper/ClientMapper.kt
> +}
Shouldn't we firstly map those to VO classes in `ClientMapper.kt`? And then in `EngineMapper` map VO to Engine?

2022-07-01 04:57 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/copiedFromSign/json_rpc/model/JsonRpcMethod.kt
> +
```suggestion
//TODO: Should there be a copy for every SDK with specific methods or one file with all methods. 
```

2022-07-01 04:57 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/copiedFromSign/json_rpc/data/JsonRpcSerializer.kt
> +
```suggestion
//TODO: Should there be a copy for every SDK with specific methods or one file with all methods. 
```

2022-07-01 04:57 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/core/model/vo/clientsync/ChatSettlementVO.kt
> +internal sealed class ChatSettlementVO : JsonRpcClientSync<ChatParamsVO> {
What do you think of renaming this to something like `ChatMethodVO`

2022-07-01 04:57 UTC, Elyniss commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/core/model/vo/clientsync/params/MediaVO.kt
> +data class MediaVO(
There already is a `MediaVO` data class in `com.walletconnect.chat.core.model.vo.Common.kt`

2022-07-01 04:57 UTC, Elyniss commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/crypto/KeyManagementRepository.kt
> +    // Needs to be added with Chat SDK
Don't worry about this. It will be removed with [PR](https://github.com/WalletConnect/WalletConnectKotlinV2/pull/228)

2022-07-04 02:27 UTC, TalhaAli00 commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +        interface PublicKeyOnSuccess : Listeners {
make sealed interface

2022-07-04 02:43 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/ChatProtocol.kt
> +//    val relay: Relay by lazy { wcKoinApp.koin.get() } //TODO: Figure out how to get relay as in Sign in here
Ya sounds good but SDKs should use the same Relay instance to keep one wss connection across all of them.

2022-07-04 02:45 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/client/mapper/ClientMapper.kt
> +}
Ya you are right as following our project rules. With sign we decided that in ClienMapper it is allowed to have EngineDO object to just to save the amount of mappers that we have to write.

Message from sign Client Mapper: 
"//TODO: Provide VO objects for engine classes. Remove using the EngineDO object in the client layer"

2022-07-04 02:49 UTC, jakobuid commented on chatSDK/chat/src/main/kotlin/com/walletconnect/chat/core/model/vo/clientsync/ChatSettlementVO.kt
> +internal sealed class ChatSettlementVO : JsonRpcClientSync<ChatParamsVO> {
Hmm I don't like it that much. It's to generic for me. But I don't have any other idea either. :p

2022-07-04 04:06 UTC, Elyniss approved these changes

2022-07-04 04:06 UTC, TalhaAli00 approved these changes

2022-07-04 04:39 UTC, merged