Added mutex locking
WalletConnect/WalletConnectKotlinV2 pull request #259
Opened 2022-07-14 15:44 UTC by Elyniss

2022-07-25 11:59 UTC, jakobuid requested changes

2022-07-25 11:59 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                wcKoinApp.modules(scarletModule(initial.relayServerUrl, jwt, initial.connectionType.toRelayConnectionType(), initial.relay))
```suggestion
                wcKoinApp.modules(scarletModule(initial.relayServerUrl.addUserAgent(), jwt, initial.connectionType.toRelayConnectionType(), initial.relay))
```
By accident?

2022-07-25 11:59 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +        awaitLock {
Should with `awaitLock`  user wait to call `extend` until e.g. `update` is executed ?

2022-07-25 14:01 UTC, TalhaAli00 approved these changes

2022-07-26 06:42 UTC, jakobuid approved these changes

2022-07-26 07:48 UTC, merged