Feature/deep linking new flow
WalletConnect/WalletConnectKotlinV2 pull request #321
Opened 2022-08-04 11:59 UTC by jakobuid

New flow of mobile deep linking between Dapp and Wallet.
Added the redirect field with native fields that enables redirection from Wallet to Dapp after handling session request.

2022-08-05 08:31 UTC, Elyniss requested changes

2022-08-05 08:31 UTC, Elyniss commented on signSDK/sign/src/main/sqldelight/migrations/1.sqm
> -ALTER TABLE PairingDao RENAME TO PairingDaoBak;
I think we cannot remove this

2022-08-05 08:31 UTC, Elyniss commented on signSDK/sign/src/main/sqldelight/migrations/1.sqm
> -ALTER TABLE SessionDao RENAME TO SessionDaoBak;
Same as above

2022-08-05 08:31 UTC, Elyniss commented on signSDK/sign/src/main/sqldelight/migrations/1.sqm
> -ALTER TABLE MetaDataDao RENAME TO MetaDataDaoBak;
Same as above

2022-08-05 08:31 UTC, Elyniss commented on signSDK/sign/src/main/sqldelight/migrations/1.sqm
> -ALTER TABLE JsonRpcHistoryDao RENAME TO JsonRpcHistoryDaoBak;
Same as above

2022-08-05 12:31 UTC, Elyniss commented on signSDK/sign/src/main/sqldelight/migrations/1.sqm
> -ALTER TABLE PairingDao RENAME TO PairingDaoBak;
@TalhaAli00 what's your take on this?

2022-08-05 12:38 UTC, jakobuid commented on signSDK/sign/src/main/sqldelight/migrations/1.sqm
> -ALTER TABLE PairingDao RENAME TO PairingDaoBak;
After calling `verifySqlDelightMigration` this line was causing test to fail

2022-08-08 08:37 UTC, Elyniss approved these changes

2022-08-09 04:09 UTC, TalhaAli00 commented on signSDK/dapp/src/main/kotlin/com/walletconnect/dapp/DappSampleApplication.kt
> +        val redirect = Sign.Model.Redirect(native = "kotlin-dapp-wc:/request")
1. Does the redirect have to be a object? Since we're only using the native property, could we potentially just have a property in Init? I don't see when the Android app would use the universal property. Please explain
2. Prior to this PR, deeplinks were split into `pairing` and `request`. Do we not want to keep this pattern for dapps?

2022-08-09 04:11 UTC, TalhaAli00 commented on signSDK/dapp/src/main/kotlin/com/walletconnect/dapp/ui/selected_account/SelectedAccountViewModel.kt
> +                    .find { session -> session.topic == requestParams.sessionTopic }?.metaData?.redirect?.native?.toUri()
I think we talked about having a simplified properties/helper functions to get the uri instead of going 3 layers deep to get the info a developer wants. Do we want to do this work later?

2022-08-09 04:13 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> +            val universal: String? = null,
follow up to the above comment, is it possible to remove this for Android?

2022-08-09 04:17 UTC, TalhaAli00 commented on signSDK/wallet/src/main/kotlin/com/walletconnect/wallet/WalletSampleApplication.kt
> +        val redirect = Sign.Model.Redirect(native = "kotlin-wallet-wc:/request")
similar comment as above. We had a separate URI for pairing vs requests. Do we not want this anymore?

2022-08-09 04:18 UTC, TalhaAli00 approved these changes

2022-08-09 07:01 UTC, jakobuid commented on signSDK/dapp/src/main/kotlin/com/walletconnect/dapp/DappSampleApplication.kt
> +        val redirect = Sign.Model.Redirect(native = "kotlin-dapp-wc:/request")
1. For me it makes sense. In db we keep only `native` field. I can't see any objection of removing `universal` and keep a structure flat. Good call. 
2. Deeplinks where always split into `pairing` and `request`.  Yes ofc we want to keep this pattern for Dapps, because it allows wallet to redirect directly to a Dapp after approving or rejecting a signing request.

2022-08-09 07:01 UTC, jakobuid commented on signSDK/dapp/src/main/kotlin/com/walletconnect/dapp/ui/selected_account/SelectedAccountViewModel.kt
> +                    .find { session -> session.topic == requestParams.sessionTopic }?.metaData?.redirect?.native?.toUri()
Nah, I can add it to this PR

2022-08-09 07:01 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> +            val universal: String? = null,
Yes

2022-08-09 07:07 UTC, jakobuid commented on signSDK/wallet/src/main/kotlin/com/walletconnect/wallet/WalletSampleApplication.kt
> +        val redirect = Sign.Model.Redirect(native = "kotlin-wallet-wc:/request")
Well, we still have separate URI for pairing and request. Nothing changes in this matter. Requests have a unique uri per wallet to avoid opening app chooser every-time when Dapp sends a request.

Could you elaborate your concern?

2022-08-09 12:36 UTC, trastvolt commented
feature/deep_linking_new_flow

2022-08-10 02:38 UTC, TalhaAli00 approved these changes

2022-08-10 13:52 UTC, merged