Feat: Add relay integration test
WalletConnect/WalletConnectKotlinV2 pull request #322
Opened 2022-08-04 12:28 UTC by Elyniss

2022-08-04 23:37 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +    fun <T> awaitLock(codeBlock: suspend () -> T): T {
why remove the private modifier?

2022-08-05 00:00 UTC, TalhaAli00 commented on signSDK/sign/src/qa/kotlin/com/walletconnect/sign/di/StorageModule.kt
> +    }
since this exact code is copied three times now, it makes more sense to move this logic into a `sharedStorageModule` file in the main directory. Then you can use Koin's `include` function with the new file and only specify the unique dependencies here

2022-08-05 00:00 UTC, TalhaAli00 commented on signSDK/sign/src/qa/kotlin/com/walletconnect/sign/di/StorageModule.kt
> +    }
same comment as above

2022-08-05 00:00 UTC, TalhaAli00 approved these changes

2022-08-05 08:12 UTC, jakobuid requested changes

2022-08-05 08:12 UTC, jakobuid commented on signSDK/sign/src/androidTest/kotlin/com/walletconnect/sign/utils/WCIntegrationActivityScenarioRule.kt
> +                val walletConnection = walletClient.isRelayConnectionAvailable.value
I think it should be enough to use `dappClient.relay.eventsFlow` and `walletClient.relay.eventsFlow` to check if the `OnConnectionOpened` is received.

2022-08-05 08:12 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +    var isRelayConnectionAvailable: StateFlow<Boolean> = _isRelayConnectionAvailable.asStateFlow()
I think we should avoid adding fields where the only reason of having them is to make test easier to write.
We should either use our current code or refactor it in the way to be more testable.
In this case I think we could use `relay.eventFlow` to check whether the connection is opened.

2022-08-05 08:12 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                signEngine.isRelayConnectionAvailable.onEach { _isRelayConnectionAvailable.value = it }.launchIn(scope)
Same

2022-08-05 08:12 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +    val isRelayConnectionAvailable = relayer.isConnectionAvailable
Same

2022-08-05 08:55 UTC, Elyniss commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +    fun <T> awaitLock(codeBlock: suspend () -> T): T {
I need some kind of locking mechanism to wait until sing is initialised before accessing the relay. I created new fun `blockUntilInitialized`. I had to create this due to having the manual configuration of the relay. I wonder if our consumers would need this as well.

2022-08-05 09:03 UTC, Elyniss commented on build.gradle.kts
> +        classpath("com.android.tools.build:gradle:7.1.3")
Yep, thanks for the remainder. I was able to figure it out. I needed to change the test package explicitly.

2022-08-05 12:04 UTC, TalhaAli00 commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +    var isRelayConnectionAvailable: StateFlow<Boolean> = _isRelayConnectionAvailable.asStateFlow()
Since we have the new variant, we can also create extension functions in classes that are only accessible to this test

2022-08-05 12:24 UTC, jakobuid approved these changes

2022-08-05 12:30 UTC, Elyniss commented on signSDK/sign/src/androidTest/kotlin/com/walletconnect/sign/relay/RelayIntegrationAndroidTest.kt
> +class RelayIntegrationAndroidTest {
That's because I added env variables to describe relay and projectId

2022-08-05 14:05 UTC, arein reviewed
Cool! Not so clear on what this test is actually testing. Seems like a bunch of refactor is also part of this.

2022-08-05 14:05 UTC, arein commented on .github/workflows/ci_relay.yml
> +      - name: Instrumentation tests
nit: why `Instrumentation`?

2022-08-05 14:07 UTC, Elyniss commented
> Cool! Not so clear on what this test is actually testing. Seems like a bunch of refactor is also part of this.

The test itself creates a session and then sends a ping

2022-08-05 14:12 UTC, Elyniss commented on .github/workflows/ci_relay.yml
> +      - name: Instrumentation tests
In the Android context, it means that it runs on an actual device. As it is only a demo file you could rename it later on.

2022-08-05 15:24 UTC, arein approved these changes

2022-08-09 04:21 UTC, TalhaAli00 approved these changes

2022-08-09 12:03 UTC, merged