Create core android module
WalletConnect/WalletConnectKotlinV2 pull request #325
Opened 2022-08-08 10:21 UTC by jakobuid

Create android core module.

2022-08-08 10:42 UTC, Elyniss commented on core/.gitignore
> +/build
This file `core/.gitignore` is not necessary

2022-08-08 10:42 UTC, Elyniss commented on core/proguard-rules.pro
> +# Add project specific ProGuard rules here.
This file `core/proguard-rules.pro` is not necessary

2022-08-08 10:43 UTC, Elyniss commented on core/proguard-rules.pro
> +# Add project specific ProGuard rules here.
Also `core/consumer-rules.pro`

2022-08-09 04:24 UTC, TalhaAli00 reviewed
Do we want to continue to call this module `Core`? Or should we change it to `Android-Core`  which will allow us to have room to create a JVM option in the future if we want?

2022-08-09 10:25 UTC, jakobuid commented
> Do we want to continue to call this module `Core`? Or should we change it to `Android-Core` which will allow us to have room to create a JVM option in the future if we want?

That was my intention. However, at some point AD neglects the `android_core` name every-time I want to use it. A module with such name cannot be find. I believe that `android` is a key words and cannot be used in the module name.

2022-08-09 10:26 UTC, jakobuid commented
> > Do we want to continue to call this module `Core`? Or should we change it to `Android-Core` which will allow us to have room to create a JVM option in the future if we want?
> 
> That was my intention. However, at some point AD neglects the `android_core` name every-time I want to use it. A module with such name cannot be find. I believe that `android` is a key words and cannot be used in the module name.

Anyway, I'd like to stress that  this module is Android specific. Do you have any other name suggestion?

2022-08-09 10:39 UTC, Elyniss requested changes

2022-08-09 10:39 UTC, Elyniss commented on foundation/src/main/java/com/walletconnect/foundation/di/ScarletModule.kt
> +import com.walletconnect.foundation.util.scope
Unfortunately I'm unable to comment in appropriate line. We need to remove line 49 from this file. `.lifecycle(get())` will cause issues because we are not providing ScarletLifecycle

2022-08-09 10:49 UTC, jakobuid commented on foundation/src/main/java/com/walletconnect/foundation/di/ScarletModule.kt
> +import com.walletconnect.foundation.util.scope
Nice catch I think it was already overlooked in foundation. I'm removing it.

2022-08-09 10:59 UTC, Elyniss requested changes

2022-08-09 10:59 UTC, Elyniss commented on buildSrc/src/main/kotlin/Dependencies.kt
>      "testImplementation"("org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion")
This might be unnecessary as it already is in `coroutinesTest()`

2022-08-09 11:34 UTC, jakobuid commented
@WalletConnect/kotlin-team It was issue with my AD, thanks to Szymon I managed to change a module name to `android_core`.

2022-08-09 11:47 UTC, TalhaAli00 approved these changes

2022-08-09 11:49 UTC, merged