feature/auth/public-api
WalletConnect/WalletConnectKotlinV2 pull request #332
Opened 2022-08-10 07:11 UTC by TalhaAli00

2022-08-10 07:43 UTC, Elyniss commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/Auth.kt
> +            sealed class Caip70: Cacao() {
I would remove it. I think it's obsolete as whole CACAO is CAIP70

2022-08-10 07:43 UTC, Elyniss commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/Auth.kt
> +                data class CacaoSignature(val t: String, val s: String, val m: String?): Caip70()
If we are using layers here I would rename it to Signature only
```suggestion
                data class Signature(val t: String, val s: String, val m: String?): Caip70()
```

2022-08-10 07:43 UTC, Elyniss commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/Auth.kt
> +        data class Respond(val id: Long, val signature: Model.Cacao.Caip70.CacaoSignature): Params()
I think it would be better it it looked like this
```suggestion
        data class Respond(val id: Long, val signature: Model.Cacao.Signature): Params()
```

2022-08-10 09:28 UTC, jakobuid requested changes

2022-08-10 09:28 UTC, jakobuid commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/Auth.kt
> +            val icons: List<String>,
AppMedaData should include `redirect` field

2022-08-10 09:28 UTC, jakobuid commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/Auth.kt
> +            sealed class Caip70: Cacao() {
I agree 👆 Cacao should be enough

2022-08-10 09:28 UTC, jakobuid commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/AuthInterface.kt
>      }
Do we want to split it to ResponderDelegate and RequesterDelegate?
I mean `onAuthRequest` will be received only by responder and `onAuthResponse` will be received only by requester.

2022-08-10 11:59 UTC, Elyniss commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/AuthInterface.kt
>      }
I'm in favour of @jakobuid proposal

2022-08-10 15:08 UTC, TalhaAli00 commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/client/Auth.kt
> +            val icons: List<String>,
added

2022-08-10 18:49 UTC, jakobuid approved these changes

2022-08-11 03:57 UTC, trastvolt commented
feature/auth/public-api

2022-08-11 07:43 UTC, Elyniss approved these changes

2022-08-11 13:24 UTC, merged

2022-08-12 10:39 UTC, Elyniss commented
@TalhaAli00 I think we merged it into wrong branch