Feature/add network and common modules
WalletConnect/WalletConnectKotlinV2 pull request #333
Opened 2022-08-10 08:17 UTC by jakobuid

Added Network and Common modules to `android_core`.

2022-08-10 13:01 UTC, TalhaAli00 reviewed
@jakobuid can you tag the issue this PR addresses?

2022-08-11 08:28 UTC, Elyniss requested changes

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/adapters/ExpiryAdapterTest.kt
> +package com.walletconnect.sign.adapters
I think this test should be in `android_core` module

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/adapters/MappingFunctionsTest.kt
>  internal class MappingFunctionsTest {
Do we need this class?

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/core/adapters/RelayerDOJsonRpcResponseJsonRpcResultJsonAdapterTest.kt
> +import com.walletconnect.android_core.common.adapters.RelayDOJsonRpcResultJsonAdapter
I think this test should be in `android_core` module

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/crypto/codec/ChaChaPolyCodecTest.kt
> +import com.walletconnect.sign.core.model.vo.Topic
wrong import. Should be `import com.walletconnect.foundation.common.model.Topic`

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/crypto/data/repository/BouncyCastleCryptoRepositoryTest.kt
> +import com.walletconnect.sign.core.model.vo.Topic
Wring import. Should be `import com.walletconnect.foundation.common.model.Topic`

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/json_rpc/domain/RelayerInteractorTest.kt
>  import com.walletconnect.sign.core.model.client.Relay
wrong import

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/json_rpc/domain/RelayerInteractorTest.kt
> +import com.walletconnect.sign.core.model.vo.Topic
wrong import

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/json_rpc/domain/RelayerInteractorTest.kt
> +import com.walletconnect.android_core.network.model.RelayDTO
wrong import

2022-08-11 08:28 UTC, Elyniss commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/ValidatorTest.kt
> +import com.walletconnect.sign.core.model.vo.Topic
wrong import

2022-08-11 09:44 UTC, jakobuid commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/adapters/MappingFunctionsTest.kt
>  internal class MappingFunctionsTest {
No, removed

2022-08-11 09:45 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/core/adapters/SubscriptionIdAdapter.kt
> -internal object SubscriptionIdAdapter: JsonAdapter<SubscriptionIdVO>() {
This adapter was moved to `foundation`. There is no point to keep this class in `sign`

2022-08-11 09:45 UTC, jakobuid commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/adapters/SubscriptionIdAdapterTest.kt
> +package com.walletconnect.sign.adapters
Yes, good call. I moved it to `foundation`

2022-08-11 09:45 UTC, jakobuid commented on signSDK/sign/src/main/kotlin/com/walletconnect/sign/core/adapters/TopicAdapter.kt
> -internal object TopicAdapter: JsonAdapter<TopicVO>() {
This adapter was moved to foundation. There is no point to keep this class in sign

2022-08-11 09:47 UTC, jakobuid commented on signSDK/sign/src/test/kotlin/com/walletconnect/sign/json_rpc/domain/RelayerInteractorTest.kt
> +import com.walletconnect.android_core.network.model.RelayDTO
This import is fine. Once RelayerInteractor is moved to `android_core` it'll compile

2022-08-11 14:26 UTC, Elyniss approved these changes

2022-08-11 14:27 UTC, TalhaAli00 approved these changes

2022-08-11 14:27 UTC, merged