Setup di and classes skeleton for Auth SDK
WalletConnect/WalletConnectKotlinV2 pull request #353
Opened 2022-08-17 12:42 UTC by jakobuid

2022-08-17 13:01 UTC, Elyniss requested changes

2022-08-17 13:01 UTC, Elyniss commented on authSDK/authsample/src/main/kotlin/com/walletconnect/authsample/AuthSampleApplication.kt
>  }
Please remove changes from authsample module to avoid conflicts

2022-08-17 20:49 UTC, TalhaAli00 commented on authSDK/auth/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET" />
maybe we move this to Android code so all SDK will have these permissions

2022-08-17 20:51 UTC, TalhaAli00 commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/di/StorageModule.kt
> +    val dbSuffix = "_auth"
we don't need a variable since it's only used once

2022-08-17 20:52 UTC, TalhaAli00 commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/di/StorageModule.kt
> +    single<ColumnAdapter<MetaDataType, String>>(named(AuthDITags.METADATA_TYPE)) { EnumColumnAdapter() }
why do we need the tag here?

2022-08-17 20:53 UTC, TalhaAli00 commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +package com.walletconnect.auth.engine.domain
add JvmSynth annotations to all internal files

2022-08-18 07:49 UTC, jakobuid commented on authSDK/auth/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.INTERNET" />
Yes good cool, I'm always down for such improvements

2022-08-18 07:55 UTC, jakobuid commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/di/StorageModule.kt
> +    single<ColumnAdapter<MetaDataType, String>>(named(AuthDITags.METADATA_TYPE)) { EnumColumnAdapter() }
Actually we don't it. Removed

2022-08-18 07:56 UTC, jakobuid commented on authSDK/auth/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +package com.walletconnect.auth.engine.domain
:ok:

2022-08-18 14:07 UTC, Elyniss commented on signSDK/sign/src/main/AndroidManifest.xml
> +    <application android:fullBackupContent="@xml/backup_rules" />
Please add backup_rules to android_core with BuildConfig values and string resource to abstract names

2022-08-18 14:07 UTC, Elyniss approved these changes

2022-08-23 13:41 UTC, merged