Feature/core/pairing client
WalletConnect/WalletConnectKotlinV2 pull request #429
Opened 2022-10-13 20:36 UTC by TalhaAli00

2022-10-15 02:54 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/Core.kt
> +        interface SessionPing : Listeners {
In terms of Core we should only talk about Pairings. SessionPing -> PairingPing

2022-10-15 02:56 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    //    private val methodsToCallbacks: MutableMap<String, (topic: String, request: WCRequest) -> Unit> = mutableMapOf()
Why do we need this commented line?

2022-10-15 02:59 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    override fun ping(ping: Core.Params.Ping, sessionPing: Core.Listeners.SessionPing?) {
We should fix naming in here, from session to pairing ping

2022-10-15 03:02 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +        return inactivePairing.runCatching {
I like this, so cool

2022-10-15 03:04 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    // TODO: add parameter to unsubscribe and publish SessionDelete from the RelayClient
I don't follow can you elaborate?

2022-10-15 03:05 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +        // TODO: Move PeerError related to either internal directory or common
Is it already done so we can remove this comment?

2022-10-15 03:05 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +            onFailure = { error -> /*TODO: add logger*/ }
Why not just adding loggers?

2022-10-15 03:11 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    }
So as we discussed, this method should be called by Sign and Auth SDKs on initialisation to avoid situation that peer receives incompatible method.

2022-10-15 03:14 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    }
Also, on pair we should return unsupported method error whe wallet calls pair and the register wasn't call on given sdk

2022-10-15 03:17 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    private fun Pairing.isValid(): Boolean = (expiry.seconds > com.walletconnect.android.internal.common.CURRENT_TIME_IN_SECONDS).also { isPairingValid ->
Package name fix

2022-10-15 03:18 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingInterface.kt
> +    // for both to subscribe on methods requests
Do we need all of those comments and commented code?

2022-10-15 03:18 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/WalletConnectScope.kt
> +//    TODO: Two scopes are defined currently!!!!
What's up with this comment?

2022-10-15 03:21 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +    private val getPendingJsonRpcHistoryEntryByIdUseCase: GetPendingJsonRpcHistoryEntryByIdUseCase,
Cool

2022-10-15 03:26 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +
Unnecessary empty lines

2022-10-15 03:33 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/client/AuthProtocol.kt
> +
Empty line

2022-10-15 03:35 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +        pairingInterface.create().fold(
What's going to happend when Dapp calls:
CoreClient.Pairing.create()
then
AuthClient.request()

2022-10-15 03:40 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +        connect: Sign.Params.Connect,
We should add @Deprecated annotation to: connect, pair and getListOfSettledPairings

2022-10-15 03:42 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +//            throw MalformedWalletConnectUri(MALFORMED_PAIRING_URI_MESSAGE)
What's up with this line?

2022-10-15 03:44 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +            val request = SessionRpcVO.SessionPropose(id = generateId(), params = sessionProposal)
SessionPropose cannot be a part of SessionRpc, because session proposals are proposed on pairing topics

2022-10-15 03:46 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                pairingInterface.updateMetadata(pairingTopic.value, peerAppMetaData, AppMetaDataType.PEER) //todo: take care of multiple metadata structures
Why peer pairing metadata is updated here?

2022-10-15 03:49 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                pairingInterface.updateMetadata(pairingTopic.value, peerAppMetaData, AppMetaDataType.PEER) //todo: take care of multiple metadata structures
and what's going on with todo?

2022-10-15 03:52 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        val proposal = request.params as SessionParamsVO.SessionProposeParams
SessionProposeParams cannot be a part of SessionParamsVO because sessions proposals are proposed on pairing topics

2022-10-15 03:53 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        val proposal = request.params as SessionParamsVO.SessionProposeParams
Why this `sessionProposalRequest.remove(proposerPublicKey)` was removed?

2022-10-15 03:57 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                    is SessionParamsVO.SessionProposeParams -> onSessionPropose(request, requestParams)
Same

2022-10-15 03:57 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                    is SessionParamsVO.SessionProposeParams -> onSessionProposalResponse(response, params)
Same

2022-10-15 04:01 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        pairingInterface.updateMetadata(pairingTopic.value, params.proposer.metadata, AppMetaDataType.PEER)
Updating pairing peer metadata here seems unnecessary

2022-10-15 04:03 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
>                  Logger.log("Session proposal reject received: ${response.error}")
Why this `if (!pairing.isActive) sequenceStorageRepository.deletePairing(pairingTopic)` got removed? It makes sense to keep it because it reduce the number of inactive pairings that do not have metadata.

2022-10-15 04:05 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/storage/sequence/SessionStorageRepository.kt
> +// todo: Also big migration
What's up with those comments? By the time we merge this PR we should be ready with such things to have final product.

2022-10-15 04:06 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/storage/sequence/SessionStorageRepository.kt
> +//        }
What's up with this?

2022-10-15 04:07 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/json_rpc/model/JsonRpcMethod.kt
>      const val WC_SESSION_PROPOSE: String = "wc_sessionPropose"
wc_sessionPropose should be a part of PairingRpc

2022-10-15 04:09 UTC, jakobuid requested changes
I've done review for those files:
- PairingClient, CoreClient, SignEngine, AuthAngine, AuthClient, SignClient

The rest is planned to be reviewed when PR doesn't have merge conflitcs.

Cann't wait to start testing peer to peer.

2022-10-15 04:12 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/WalletConnectScope.kt
> +//    TODO: Two scopes are defined currently!!!!
the scope variable is defined twice in the app, we need to make it a single instance

2022-10-17 12:22 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/storage/PairingStorageRepositoryInterface.kt
> +//todo: seperate interface might not be necessary
remove

2022-10-17 12:23 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingInterface.kt
> +//todo: add ( onError: (Core.Model.Error) -> Unit) parameter to accessible functions
remove

2022-10-17 12:23 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PeerError.kt
> +}
I don't think this should be in pairing package

2022-10-18 11:21 UTC, jakobuid commented on androidCore/impl/src/release/kotlin/com.walletconnect.android.impl.di/StorageModule.kt
> +        AndroidSqliteDriver(
Why are there two instances of database?

2022-10-18 11:23 UTC, jakobuid commented on androidCore/impl/build.gradle.kts
> +//    releaseApi("com.walletconnect:android-core-common:1.0.0")
Pls let's not leave commented code. If not used let's remove it

2022-10-18 11:32 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/WalletConnectScope.kt
> +//    TODO: Two scopes are defined currently!!!!
so instead of leaving a todo comment, why not making it a single instance?

2022-10-18 11:35 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/Validator.kt
> +        if (!mapOfQueryParameters.containsKey("methods")) return null
I think this condition is not right, because with current state of work we don't support registered methods param in URL so everytime while scanning qr kotlin/js/swift dapp it'll throw an error.

2022-10-18 11:37 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    override fun ping(ping: Core.Params.Ping, sessionPing: Core.Listeners.SessionPing?) {
SessionPing -> PairingPing

2022-10-18 11:39 UTC, jakobuid commented on auth/responder/src/main/kotlin/com/walletconnect/responder/ui/accounts/AccountsViewModel.kt
> +//        AuthClient.pair(pairingParams) { error -> Log.e(tag(this), error.throwable.stackTraceToString()) }
Let's uncomment this and have a full working integration with CoreClient

2022-10-18 11:42 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
> +    lateinit var selfMetaData: Core.Model.AppMetaData
Can be private

2022-10-18 11:43 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
> +    val Relay: RelayConnectionInterface = RelayClient
Do we allow developers to implement RelayConnectionInterface?

2022-10-18 11:44 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/CommonModule.kt
> +    //todo: Maybe this needs to be registered as named(AndroidCommonDITags.MOSHI) to properly work with new JsonRpcSerializer approach
What's up with this todo? Let's tackle it

2022-10-18 11:45 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/EngineModule.kt
> +        //todo: check if dependencies are here
Again, let's just tackle what todo says instead of leaving it for later

2022-10-18 11:47 UTC, jakobuid commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/copiedFromSign/core/exceptions/client/ClientExceptions.kt
> +// TODO: Replace with exceptions defined in Android Core SDK or reduce to domain specific exceptions
Again, let's tackle this todo and please remove uncommented code

2022-10-18 11:48 UTC, jakobuid commented on sign/sdk/build.gradle.kts
> +//    releaseImplementation("com.walletconnect:android-core-impl:1.0.0")
What's up with this line?

2022-10-18 11:50 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/session/SessionRpcVO.kt
> +    internal data class SessionPropose(
SessionPropose is a part of PairingRpc

2022-10-18 11:52 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/CommonModule.kt
> +    //todo: Maybe this needs to be registered as named(AndroidCommonDITags.MOSHI) to properly work with new JsonRpcSerializer approach
Same

2022-10-18 11:52 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +    //todo: check if dependencies are here
Same

2022-10-18 11:53 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +    //todo: check if dependencies are here
Same

2022-10-18 11:54 UTC, jakobuid commented on sign/wallet/build.gradle.kts
> +//    releaseImplementation("com.walletconnect:sign:2.0.0-rc.5")
What's up with this?

2022-10-19 01:55 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    //    private val methodsToCallbacks: MutableMap<String, (topic: String, request: WCRequest) -> Unit> = mutableMapOf()
removed

2022-10-19 01:57 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +        // TODO: Move PeerError related to either internal directory or common
removed

2022-10-19 02:02 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +    }
Register is now called. Pair logic has been updated.

2022-10-19 02:04 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingInterface.kt
> +    // for both to subscribe on methods requests
Comments help explain the functions, I don't see a downside of having them. But if you want them removed, I can remove them. Also removed commented code

2022-10-19 02:14 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/WalletConnectScope.kt
> +//    TODO: Two scopes are defined currently!!!!
removed other instance

2022-10-19 02:15 UTC, TalhaAli00 commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +
fixed

2022-10-19 02:16 UTC, TalhaAli00 commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/client/AuthProtocol.kt
> +
fixed

2022-10-19 11:30 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +//            throw MalformedWalletConnectUri(MALFORMED_PAIRING_URI_MESSAGE)
removed

2022-10-19 11:32 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +            val request = SessionRpcVO.SessionPropose(id = generateId(), params = sessionProposal)
Let's have a discussion about this. To me, it feels confusing to have a `PairingRpcVO` just for session proposal since we've moved everything related to pairing into the Pairing API.

2022-10-19 11:42 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                pairingInterface.updateMetadata(pairingTopic.value, peerAppMetaData, AppMetaDataType.PEER) //todo: take care of multiple metadata structures
good catch. Moved peer pairing metadata to `onSessionProposal`

2022-10-19 11:42 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                pairingInterface.updateMetadata(pairingTopic.value, peerAppMetaData, AppMetaDataType.PEER) //todo: take care of multiple metadata structures
as for the TODO, I'm not sure. Szymon added it so we'll need to sync up and see

2022-10-19 12:09 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        val proposal = request.params as SessionParamsVO.SessionProposeParams
good catch. Added back

2022-10-19 12:11 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        pairingInterface.updateMetadata(pairingTopic.value, params.proposer.metadata, AppMetaDataType.PEER)
can you explain what you mean by unnecessary?

2022-10-19 12:13 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
>                  Logger.log("Session proposal reject received: ${response.error}")
we set the pairing to activate above before the when. The check will always fail since the pairing will always be active by this point

2022-10-19 12:14 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/storage/sequence/SessionStorageRepository.kt
> +// todo: Also big migration
I'm not sure, we'll have to check with Szymon about these

2022-10-19 12:36 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/storage/sequence/SessionStorageRepository.kt
> +//        }
removed

2022-10-19 12:38 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/model/AppMetaDataType.kt
> +    SELF, PEER, UNSPECIFIED
removed

2022-10-19 12:42 UTC, TalhaAli00 commented on androidCore/impl/src/release/kotlin/com.walletconnect.android.impl.di/StorageModule.kt
> +        AndroidSqliteDriver(
are you asking about this specific DB?

2022-10-19 12:43 UTC, TalhaAli00 commented on androidCore/impl/build.gradle.kts
> +//    releaseApi("com.walletconnect:android-core-common:1.0.0")
removed

2022-10-19 12:43 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/storage/PairingStorageRepositoryInterface.kt
> +//todo: seperate interface might not be necessary
this has been removed

2022-10-19 12:45 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/Validator.kt
> +        if (!mapOfQueryParameters.containsKey("methods")) return null
There is a PR up to add this logic for the other platforms. Once all platforms are on the same page, it should work correctly

2022-10-19 12:46 UTC, TalhaAli00 commented on auth/responder/src/main/kotlin/com/walletconnect/responder/ui/accounts/AccountsViewModel.kt
> +//        AuthClient.pair(pairingParams) { error -> Log.e(tag(this), error.throwable.stackTraceToString()) }
updated

2022-10-19 12:47 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
> +    lateinit var selfMetaData: Core.Model.AppMetaData
just removed it since it wasn't being used

2022-10-19 12:59 UTC, TalhaAli00 commented on sign/sdk/build.gradle.kts
> +//    releaseImplementation("com.walletconnect:android-core-impl:1.0.0")
this is just for testing purposes. It will be reverted back. We'll have to keep doing making changes like these to test release builds until we come up with a staging environment

2022-10-19 13:00 UTC, TalhaAli00 commented on sign/wallet/build.gradle.kts
> +//    releaseImplementation("com.walletconnect:sign:2.0.0-rc.5")
same as above

2022-10-19 14:33 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingInterface.kt
> +    // for both to subscribe on methods requests
fixed

2022-10-19 14:34 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +            val request = SessionRpcVO.SessionPropose(id = generateId(), params = sessionProposal)
changed to SignRpcVO

2022-10-19 14:37 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                    is SessionParamsVO.SessionProposeParams -> onSessionPropose(request, requestParams)
done with renaming of Rpc class

2022-10-19 14:37 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                    is SessionParamsVO.SessionProposeParams -> onSessionProposalResponse(response, params)
done with renaming of Rpc class

2022-10-19 14:40 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        pairingInterface.updateMetadata(pairingTopic.value, params.proposer.metadata, AppMetaDataType.PEER)
we're ok with this addition

2022-10-19 14:40 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
>                  Logger.log("Session proposal reject received: ${response.error}")
logic checks out

2022-10-19 14:48 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/storage/sequence/SessionStorageRepository.kt
> +// todo: Also big migration
removed todos

2022-10-19 14:49 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/Validator.kt
> +        if (!mapOfQueryParameters.containsKey("methods")) return null
commented out

2022-10-19 14:49 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/session/SessionRpcVO.kt
> +    internal data class SessionPropose(
done with renaming of Rpc class

2022-10-21 05:52 UTC, TalhaAli00 commented
@jakobuid @Elyniss PR is ready to merge

2022-10-21 09:59 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +                onPairing(pairing.uri)
Why this method returns in callback `pairing.uri`? I think this should be responsibility of PairingClient create a pairing and then pass the pairing topic all the way to the request method to publish auth_request on it.

2022-10-21 10:01 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +        } ?: return
It seems necessary here because the reason of having the PairingClient is to extract pairing creation from AuthSDK. Once Pairing is created by PairingClient, a pairing topic should be passed all the way to the auth request method.

2022-10-21 10:20 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
> +                connect.pairing.toPairing(), onProposedSequence
We can simplify it even more, I think we don't need `onProposedSequence` anymore

2022-10-21 10:23 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        onProposedSequence: () -> Unit,
This is unnecessary here

2022-10-21 10:28 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/json_rpc/data/JsonRpcSerializer.kt
>  //todo: Verify if consequent initialisations of child class append moshi adapters and store entries.
Let's just verify and remove todo

2022-10-21 10:28 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/json_rpc/domain/JsonRpcInteractor.kt
> +            } ?: handleError("JsonRpcInteractoraklsfhj: Unknown result params")
`JsonRpcInteractoraklsfhj` ?

2022-10-21 10:33 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
> +            single<RelayConnectionInterface> { RelayClient }
With this line, do we allow developers to use their implementation of `RelayConnectionInterface` in our system?

2022-10-21 10:37 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
> +            single<RelayConnectionInterface> { RelayClient }
Shouldn't there be: `single<RelayConnectionInterface> { Relay }` ?

2022-10-21 10:38 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
>          with(initial) {
`with` can be removed

2022-10-21 10:41 UTC, jakobuid commented on sign/sdk/src/main/sqldelight/migrations/1.sqm
Why files like 1.sqm, 2.sqm and 3.sqm have been changed?

2022-10-21 10:45 UTC, jakobuid reviewed
@TalhaAli00 @Elyniss 
While testing Dapp and Wallet I got crash on deep-linking communication

<img width="1013" alt="Screenshot 2022-10-21 at 12 45 42" src="https://user-images.githubusercontent.com/23366251/197178359-6334b560-1a93-4612-b4b7-8b6071d50beb.png">

2022-10-21 14:02 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/CoreClient.kt
> +            single<RelayConnectionInterface> { RelayClient }
changed

2022-10-21 14:02 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
>          with(initial) {
removed

2022-10-21 14:03 UTC, TalhaAli00 commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/json_rpc/domain/JsonRpcInteractor.kt
> +            } ?: handleError("JsonRpcInteractoraklsfhj: Unknown result params")
changed back

2022-10-21 15:23 UTC, jakobuid approved these changes

2022-10-23 13:49 UTC, TalhaAli00 commented on sign/sdk/src/main/sqldelight/migrations/1.sqm
discussed

2022-10-23 13:49 UTC, TalhaAli00 commented on androidCore/impl/src/release/kotlin/com.walletconnect.android.impl.di/StorageModule.kt
> +        AndroidSqliteDriver(
discussed. Core and SDK now have different DBs

2022-10-23 13:50 UTC, TalhaAli00 commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/EngineModule.kt
> +        //todo: check if dependencies are here
removed

2022-10-23 13:50 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/CommonModule.kt
> +    //todo: Maybe this needs to be registered as named(AndroidCommonDITags.MOSHI) to properly work with new JsonRpcSerializer approach
removed

2022-10-23 13:51 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +    //todo: check if dependencies are here
removed

2022-10-23 13:51 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/EngineModule.kt
> +    //todo: check if dependencies are here
removed

2022-10-24 07:41 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        val sessionProposal: SessionParamsVO.SessionProposeParams = toSessionProposeParams(listOf(relay), namespaces, selfPublicKey, selfAppMetaData)
Please change also: `SessionParamsVO -> SignParamsVO`

2022-10-24 12:27 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +        val sessionProposal: SessionParamsVO.SessionProposeParams = toSessionProposeParams(listOf(relay), namespaces, selfPublicKey, selfAppMetaData)
renamed

2022-10-24 13:55 UTC, Elyniss approved these changes

2022-10-24 13:55 UTC, Elyniss commented on auth/sdk/build.gradle.kts
> +    extra[KEY_PUBLISH_VERSION] = "1.0.0-alpha02"
```suggestion
    extra[KEY_PUBLISH_VERSION] = "1.0.0"
```

2022-10-24 13:55 UTC, Elyniss commented on sign/sdk/build.gradle.kts
> +    extra[KEY_PUBLISH_VERSION] = "2.0.0-rc.6"
```suggestion
    extra[KEY_PUBLISH_VERSION] = "2.0.0"
```

2022-10-24 13:55 UTC, Elyniss commented on sign/wallet/build.gradle.kts
> +//    releaseImplementation("com.walletconnect:sign:2.0.0-rc.5")
```suggestion

```

2022-10-24 14:16 UTC, merged