Integrate android core into chat sdk
WalletConnect/WalletConnectKotlinV2 pull request #433
Opened 2022-10-25 09:31 UTC by jakobuid

2022-10-25 09:32 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/data/repository/BouncyCastleKeyManagementRepository.kt
> +    // Added with Chat SDK
Within next issue BouncyCastleKeyManagementRepository is going to be refactored

2022-10-25 09:33 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/storage/KeyChain.kt
> +    // Added With Chat SDK
Within next issue KeyChain is going to be refactored

2022-10-25 09:55 UTC, Elyniss commented on auth/sdk/build.gradle.kts
> +        buildConfigField(type = "String", name = "sdkVersion", value = "\"1.0.0-alpha01\"")
I just noticed, we should use previously defined sdkVersion
```
        buildConfigField(type = "String", name = "sdkVersion", value = "\"${requireNotNull(extra.get(KEY_PUBLISH_VERSION))}\"")

```

2022-10-25 09:55 UTC, Elyniss commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +    private val jsonRpcInteractor: JsonRpcInteractorInterface,
Wrong place for comments, but files `JsonRpcSerializer` and `JsonRpcInteractor` are empty. Why are they added?

2022-10-25 09:55 UTC, Elyniss commented on chat/sdk/build.gradle.kts
> +    database("Database") {
Can we call it ChatDatabase?

2022-10-25 09:55 UTC, Elyniss commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/client/Chat.kt
> +            fun isValid() = com.walletconnect.chat.common.model.AccountId(value).isValid()
remove package

2022-10-25 09:55 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +    private val jsonRpcInteractor: JsonRpcInteractorInterface,
Wrong place for comment. `JsonRpcSerializer` was added. Why?

2022-10-25 10:04 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/engine/domain/AuthEngine.kt
> +    private val jsonRpcInteractor: JsonRpcInteractorInterface,
Because before last android-core update they were required :) They are just not deleted while merging

2022-10-25 10:04 UTC, jakobuid commented on chat/sdk/build.gradle.kts
> +    database("Database") {
Yes we can

2022-10-25 10:05 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +    private val jsonRpcInteractor: JsonRpcInteractorInterface,
The same answer as above

2022-10-25 13:12 UTC, TalhaAli00 commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/data/repository/BouncyCastleKeyManagementRepository.kt
> +    // Added with Chat SDK
Do you mean you will extract all methods with "Added for Chat" into a separate file?

2022-10-25 13:21 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/data/repository/BouncyCastleKeyManagementRepository.kt
> +    // Added with Chat SDK
Oh no, it doesn't make sense to me. I'm going to simplify the whole class, remove unnecessary methods and make it more reusable across sdks

2022-10-25 13:58 UTC, TalhaAli00 requested changes

2022-10-25 13:58 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/model/Tags.kt
> -    //todo: Discuss: Should Tags be in specific SDKs?
I think we should discuss this before removing it

2022-10-26 06:53 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/model/Tags.kt
> -    //todo: Discuss: Should Tags be in specific SDKs?
Reverted. Let's do it then on our next sync. I'd like to tackle our todos because we have many of them recently.

2022-10-26 06:54 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/PairingClient.kt
> +        jsonRpcInteractor.publishJsonRpcRequest(Topic(topic), irnParams, pairingDelete,
I agree but here: `publishJsonRpcRequests` -> `publishJsonRpcRequest` which makes way more sense

2022-10-26 06:56 UTC, jakobuid commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/client/mapper/ClientMapper.kt
> +internal fun Chat.Model.AccountId.toVO(): AccountId {
nice catch

2022-10-26 06:58 UTC, jakobuid commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/common/adapter/JsonRpcResultAdapter.kt
> +            value_.result is String && (value_.result as String).startsWith("{") -> {
I guess yes otherwise it does not compile

2022-10-26 07:00 UTC, jakobuid commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
> +            { Logger.log("Chat invite sent successfully") },
I cannot see benefit. With singleton we're having less params in ChatEngine constructor

2022-10-26 07:50 UTC, Elyniss approved these changes

2022-10-27 07:28 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/storage/KeyChain.kt
> +    // Added With Chat SDK
The same answer as above. Remove unnecessary methods and make this class reusable across all sdks

2022-10-27 13:08 UTC, TalhaAli00 approved these changes

2022-10-27 13:11 UTC, TalhaAli00 commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/engine/domain/ChatEngine.kt
> +            { Logger.log("Chat invite sent successfully") },
we were originally planning on removing the singleton because we don't have a way of creating the singleton in the foundation module. We've already created a logger instance in Koin, so let's use it as we have been or find a way to create a singleton that can be used

2022-10-27 13:27 UTC, merged