Feature/push/setup wallet engine
WalletConnect/WalletConnectKotlinV2 pull request #531
Opened 2022-12-15 01:05 UTC by TalhaAli00

2022-12-15 10:17 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/model/EngineDO.kt
> +        val metadata: AppMetaData,
What about keeping Push convention as a prefix? This way we could match Push specs. E.g. PushSubscription

2022-12-15 10:18 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/model/EngineDO.kt
> +    data class Message(
The same comment here. PushMessage is more meaningful, what do you think?

2022-12-15 10:28 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/Push.kt
> +            class Init(): Params()
We need CoreClient as a param inside Init()

2022-12-15 10:32 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/WalletProtocol.kt
> +            // TODO: Find out if it's better to pass the publicKey instead of the ID
It depends how you're planning to store PushSubscriptions. IMO it can be both, however passing ID looks cleaner

2022-12-15 10:34 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/WalletProtocol.kt
> +            onError(Push.Wallet.Model.Error(it))
Small one, can we replace it with a name?

2022-12-15 10:37 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/DecryptMessageUseCase.kt
> +    operator fun invoke(key: String, message: String): String {
Looking at the WalletProtocol, we're passing here topic not key

2022-12-15 10:47 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/WalletEngine.kt
> +            // TODO: Should we automatically respondWithSuccess?
Looking at the specs, you're right

2022-12-15 10:49 UTC, jakobuid commented on push/sdk/build.gradle.kts
> +    extra[KEY_PUBLISH_VERSION] = "2.3.1"
1.0.0

2022-12-15 10:52 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/data/codec/ChaChaPolyCodec.kt
> +    override fun decryptMessage(key: String, cipherText: String): String {
Note:
Instead of key, we're passing topic, so inside this function we should use `keyManagementRepository.getSymmetricKey(topic)` to get SymKey

2022-12-15 10:53 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/crypto/Codec.kt
> +    fun decryptMessage(key: String, cipherText: String): String //TODO: Maybe this needs to be an extension function instead
I like the idea of using extension function

2022-12-18 16:01 UTC, Elyniss commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/model/EngineMappter.kt
> +package com.walletconnect.push.common.model
File has a typo

2022-12-18 16:13 UTC, Elyniss commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/WalletProtocol.kt
> +    private lateinit var pushEngine: WalletEngine
```suggestion
    private lateinit var walletEngine: WalletEngine
```

2022-12-18 16:16 UTC, Elyniss commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/WalletEngine.kt
> +//                        resubscribeToSubscriptions()
Why are we not resubscribing?

2022-12-19 15:14 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/model/EngineDO.kt
> +        val metadata: AppMetaData,
added prefix

2022-12-19 15:14 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/model/EngineDO.kt
> +    data class Message(
addressed

2022-12-19 15:14 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/Push.kt
> +            class Init(): Params()
added

2022-12-19 15:16 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/WalletProtocol.kt
> +            onError(Push.Wallet.Model.Error(it))
addressed

2022-12-19 15:17 UTC, TalhaAli00 commented on push/sdk/build.gradle.kts
> +    extra[KEY_PUBLISH_VERSION] = "2.3.1"
addressed

2022-12-19 15:20 UTC, TalhaAli00 commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/crypto/Codec.kt
> +    fun decryptMessage(key: String, cipherText: String): String //TODO: Maybe this needs to be an extension function instead
not valid

2022-12-19 15:20 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/common/model/EngineMappter.kt
> +package com.walletconnect.push.common.model
fixed

2022-12-19 15:21 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/WalletProtocol.kt
> +    private lateinit var pushEngine: WalletEngine
done

2022-12-19 15:21 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/WalletEngine.kt
> +//                        resubscribeToSubscriptions()
will add to both once done

2022-12-20 08:07 UTC, jakobuid requested changes

2022-12-20 08:07 UTC, jakobuid commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/DecryptMessageUseCase.kt
> +    operator fun invoke(topic: String, message: String): String {
Hey, we agreed to remove it

2022-12-21 03:58 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/DecryptMessageUseCase.kt
> +    operator fun invoke(topic: String, message: String): String {
updates were in another branch. Moved them here as well

2022-12-21 03:58 UTC, TalhaAli00 commented on push/sdk/src/main/kotlin/com/walletconnect/push/wallet/engine/domain/WalletEngine.kt
> +//                        resubscribeToSubscriptions()
added to branch with dapp

2022-12-21 09:03 UTC, Elyniss approved these changes

2022-12-21 12:20 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/crypto/Codec.kt
> +    }
We agreed that `decryptPayload` and companion object is not needed here

2022-12-21 12:21 UTC, jakobuid requested changes

2022-12-21 12:21 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/crypto/Codec.kt
> +    }
We agreed that `decryptPayload` and companion object is not needed here

2022-12-21 13:33 UTC, TalhaAli00 commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/crypto/Codec.kt
> +    }
this is done

2022-12-21 14:21 UTC, jakobuid approved these changes

2022-12-21 15:01 UTC, merged