Add wallet module along with sdk
WalletConnect/WalletConnectKotlinV2 pull request #535
Opened 2022-12-16 08:30 UTC by jakobuid

…nV2 into feature/wallet_sdk

2022-12-20 13:54 UTC, Elyniss commented on androidCore/impl/src/debug/kotlin/com/walletconnect/android/impl/di/StorageModule.kt
We should add it also to release variant

2022-12-20 13:54 UTC, Elyniss commented on auth/responder/build.gradle.kts
> +//    releaseImplementation("com.walletconnect:auth")
remove before merge

2022-12-20 13:54 UTC, Elyniss commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/CommonModule.kt
>  internal fun commonModule() = module {
Why is it not being called?

2022-12-20 21:43 UTC, TalhaAli00 commented on androidCore/impl/src/debug/kotlin/com/walletconnect/android/impl/di/StorageModule.kt
>      }
This can maybe also be done so that we only do the get call once.

```suggestion
   wcKoinApp.koin.getOrNull<SqlDriver>(named(AndroidCoreDITags.ANDROID_CORE_DATABASE_DRIVER) 
       ?: single<SqlDriver>(named(AndroidCoreDITags.ANDROID_CORE_DATABASE_DRIVER)) {
            AndroidSqliteDriver(
                schema = AndroidCoreDatabase.Schema,
                context = androidContext(),
                name = DBNames.ANDROID_CORE_DB_NAME,
            )
        }
    
```

2022-12-20 21:43 UTC, TalhaAli00 commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/di/BaseStorageModule.kt
>      }
if the above suggestion works, let's use that for all of these checks

2022-12-20 22:00 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/JsonRpcResponse.kt
> +import com.walletconnect.android.internal.common.model.type.SerializableJsonRpc
Was this added because the file was moved?

2022-12-20 22:11 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/adapter/JsonRpcResultAdapter.kt
> +internal class JsonRpcResultAdapter(val moshi: Moshi) : JsonAdapter<JsonRpcResponse.JsonRpcResult>() {
Can we add a TODO to revisit this topic? I think I have a solution that is similar to how we handle serialization

2022-12-21 04:04 UTC, TalhaAli00 commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/relay/RelayClient.kt
> +        wsConnectionFailedFlow.onEach { walletConnectException -> onError(walletConnectException) }.launchIn(scope)
at this point, I think we can just get rid of the variable and just do the collection either directly here or in a function

2022-12-21 04:07 UTC, TalhaAli00 commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/CommonModule.kt
>      includes(androidCommonModule())
let's just move the `androidCommonModule` into the AuthProtocol class and remove this

2022-12-21 04:12 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> -        data class RelayProtocolOptions(val protocol: String, val data: String? = null) : Model()
let's also add a deprecation message here in case people are using this somewhere

2022-12-21 04:12 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> -    enum class ConnectionType {
same comment about deprecation

2022-12-21 04:12 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
>      @Deprecated(
I agree. Anything public facing should be deprecated

2022-12-21 04:15 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +            .filter { request -> request.params is SignParams } //todo: should be here?
the filter is just extra protection

2022-12-21 04:17 UTC, TalhaAli00 commented on web3/wallet/build.gradle.kts
> +    releaseImplementation("com.walletconnect:sign:2.4.0")
let's switch to using the version variables instead

2022-12-22 06:24 UTC, jakobuid commented on androidCore/impl/src/debug/kotlin/com/walletconnect/android/impl/di/StorageModule.kt
Good catch, addressed

2022-12-22 06:44 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/CommonModule.kt
>  internal fun commonModule() = module {
Because I thought we can avoid this, however it's still needed in the scenario where the user injects its own RelayClient

2022-12-22 06:45 UTC, jakobuid commented on chat/sdk/src/main/kotlin/com/walletconnect/chat/di/CommonModule.kt
>  internal fun commonModule() = module {
same

2022-12-22 06:45 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
>      @Deprecated(
Good catch, agreed

2022-12-22 06:50 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/CommonModule.kt
>  internal fun commonModule() = module {
Addressed

2022-12-22 06:50 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> +        data class DeletedSession(val topic: String, val reason: String) : Model()
👌

2022-12-22 07:03 UTC, jakobuid commented on androidCore/impl/src/debug/kotlin/com/walletconnect/android/impl/di/StorageModule.kt
>      }
I replaced all places

2022-12-22 07:11 UTC, jakobuid commented on androidCore/impl/src/main/kotlin/com/walletconnect/android/impl/di/BaseStorageModule.kt
>      }
👍

2022-12-22 07:12 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/JsonRpcResponse.kt
> +import com.walletconnect.android.internal.common.model.type.SerializableJsonRpc
Just moved

2022-12-22 07:12 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/adapter/JsonRpcResultAdapter.kt
> +internal class JsonRpcResultAdapter(val moshi: Moshi) : JsonAdapter<JsonRpcResponse.JsonRpcResult>() {
Sure

2022-12-22 07:15 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/relay/RelayClient.kt
> +        wsConnectionFailedFlow.onEach { walletConnectException -> onError(walletConnectException) }.launchIn(scope)
done

2022-12-22 07:17 UTC, jakobuid commented on auth/sdk/src/main/kotlin/com/walletconnect/auth/di/CommonModule.kt
>      includes(androidCommonModule())
Makes sense

2022-12-22 07:20 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> -        data class RelayProtocolOptions(val protocol: String, val data: String? = null) : Model()
👌

2022-12-22 07:20 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> -    enum class ConnectionType {
👌

2022-12-22 07:20 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +            .filter { request -> request.params is SignParams } //todo: should be here?
Agreed

2022-12-22 07:21 UTC, jakobuid commented on web3/wallet/build.gradle.kts
> +    releaseImplementation("com.walletconnect:sign:2.4.0")
Agreed

2022-12-22 09:56 UTC, Elyniss requested changes

2022-12-22 09:56 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        message = "Getting a list of settled sessions by to[ic is replaced with getSettledSessionByTopic()",
```suggestion
        message = "Getting a list of settled sessions by topic is replaced with getSettledSessionByTopic()",
```

2022-12-22 11:08 UTC, Elyniss commented on web3/wallet/ReadMe.md
> +Web3Wallet SDK introduces a new interface for all the wallet users that wraps the Sign and Auth clients internally. Only one dependence is needed to
```suggestion
Web3Wallet SDK introduces a new interface for all the wallet users that wraps the Sign and Auth clients internally. Only one dependency is needed to
```

2022-12-22 11:11 UTC, Elyniss commented on web3/wallet/ReadMe.md
> +val rejectParams = Sign.Params.Reject = Reject(proposerPublicKey, rejectionReason, rejectionCode)
```suggestion
val rejectParams: Sign.Params.Reject = Sign.Params.Reject(proposerPublicKey, rejectionReason, rejectionCode)
```

2022-12-22 13:29 UTC, Elyniss approved these changes

2022-12-22 13:31 UTC, Elyniss commented on web3/wallet/ReadMe.md
> +val payloadParams: Wallwt.Model.PayloadParams  = //PayloadParams received in the onAuthRequest callback
```suggestion
val payloadParams: Wallet.Model.PayloadParams  = //PayloadParams received in the onAuthRequest callback
```

2022-12-22 15:47 UTC, TalhaAli00 commented on ReadMe.md
> +| 1.1.0 | 1.6.0                   |                           | 2.4.0            |                  |                  |
Shouldn't we put the W3Wversion here?

2022-12-22 15:51 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> +        message = "ConnectionType a pairing is be moved to CoreClient",
```suggestion
        message = "ConnectionType for the relay is moved to CoreClient",
```

2022-12-22 15:52 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        fun onSessionDelete(deletedSession: Sign.Model.SessionDelete)
We should keep the old function and add deprecated to it as well. Without this, the release will be a breaking change

2022-12-22 15:53 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        fun onSessionDelete(deletedSession: Sign.Model.SessionDelete)
same as above

2022-12-22 15:53 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        onError: (Sign.Model.Error) -> Unit
same

2022-12-22 15:55 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
>                  is EngineDO.SessionDelete -> delegate.onSessionDelete(event.toClientDeletedSession())
With the change of having both the old and new delete functions, we should emit to both of them here

2022-12-22 15:56 UTC, TalhaAli00 commented on web3/wallet/ReadMe.md
> +```
Should we also show an example using the BOM?

2022-12-22 15:57 UTC, TalhaAli00 commented on web3/wallet/ReadMe.md
> +Web3Wallet SDK introduces a new interface for all the wallet users that wraps the Sign and Auth clients internally. Only one dependency is needed to
```suggestion
Web3Wallet SDK introduces a new interface for all wallets that wraps the Sign and Auth clients internally. Only one dependency is needed to
```

2022-12-22 17:45 UTC, jakobuid commented on ReadMe.md
> +| 1.1.0 | 1.6.0                   |                           | 2.4.0            |                  |                  |
Yup, adding a version

2022-12-22 17:50 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        fun onSessionDelete(deletedSession: Sign.Model.SessionDelete)
Yea this is true, the more I think about it the more I lean toward keeping the old naming. From devs perspective, it only creates unnecessary ambiguity, the would have to add a new callback and keep the old one at the same time

2022-12-22 17:51 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        fun onSessionDelete(deletedSession: Sign.Model.SessionDelete)
same

2022-12-22 17:52 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        onError: (Sign.Model.Error) -> Unit
what do you mean here? This one hasn't changed

2022-12-22 17:52 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignProtocol.kt
>                  is EngineDO.SessionDelete -> delegate.onSessionDelete(event.toClientDeletedSession())
Same

2022-12-22 17:53 UTC, jakobuid commented on web3/wallet/ReadMe.md
> +```
I can add it, to keep it consistent will add it to all ReadMes

2022-12-23 08:05 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +        fun onSessionDelete(deletedSession: Sign.Model.SessionDelete)
Reverted

2022-12-23 14:13 UTC, TalhaAli00 approved these changes

2022-12-23 14:15 UTC, merged