✨Implement basic success callbacks
WalletConnect/WalletConnectKotlinV2 pull request #558
Opened 2023-01-02 15:18 UTC by mitsinsar

I've added success callbacks with default values to make them compatible with previous version.

Also a suggestion; using linters like ktlint or detekt would be a nice touch for consistency.

2023-01-02 15:20 UTC, Elyniss commented
Christmas in January! Thanks, @mitsinsar I will happily review it soon!

2023-01-03 11:02 UTC, jakobuid commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/pairing/engine/domain/PairingEngine.kt
> +    fun pair(uri: String, onSuccess: (String) -> Unit, onFailure: (Throwable) -> Unit) {
It should be enough to have an empty callback because we return a type from the protocol layer

2023-01-03 11:03 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/SignInterface.kt
> +    fun disconnect(disconnect: Sign.Params.Disconnect, onSuccess: (String) -> Unit = {}, onError: (Sign.Model.Error) -> Unit)
Let's keep things consistent and use corresponding methods params types in all callbacks instead of returning primitives

2023-01-03 11:08 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +            onError = { onError(it) }
Let's use named lambda param

2023-01-03 11:14 UTC, jakobuid requested changes
Thanks for contribution :)

Left couple of comments to keep things in a consistent way. One note that I didn't left in the code is that we could keep all onSuccess callback in the engine layer without any params, if we decide to return a type in the protocol layer.

Also, @WalletConnect/kotlin-team since we're willing to merge this PR soon we should add corresponding onSuccess callbacks in the web3wallet and auth sdks. Issue: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/559

2023-01-03 11:52 UTC, Elyniss requested changes
Due to interface changes on `JsonRpcInteractor.subscribe` tests at https://github.com/WalletConnect/WalletConnectKotlinV2/blob/854e0497b1ec668e692e49315e67f5f53b39e1ae/androidCore/impl/src/test/kotlin/com/walletconnect/android/impl/json_rpc/domain/RelayerInteractorTest.kt#L223 are failing. Could you change the tests as well?

2023-01-03 12:47 UTC, mitsinsar commented
Hello, @Elyniss , @jakobuid! Thank you for your review. I implemented requested changes. 

Additionally, I gave default param to success callback of `pair` function in SignInterface to make things consistent. 

I can revert this change if need.

Thanks!

2023-01-03 13:08 UTC, Elyniss approved these changes
I just run the failing tests locally to confirm they pass. All good on my side. Thank for the contribution and btw great work on pera wallet!

2023-01-03 14:31 UTC, mitsinsar commented
Thank you so much @Elyniss , we also appreciate your contribution to the community. 

I'll be waiting Jakup to resolve conversations, then I'll merge, I believe.

2023-01-03 15:21 UTC, jakobuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +    internal fun pair(uri: String, onSuccess: (String) -> Unit, onFailure: (Throwable) -> Unit) {
Let's make all onSuccess callbacks in the SignEngine without any parameters as well. There is no need for them because we're returning the protocol layer types directly.

2023-01-04 13:17 UTC, jakobuid approved these changes

2023-01-04 13:39 UTC, merged