feat: remove namespaces extensions
WalletConnect/WalletConnectKotlinV2 pull request #610
Opened 2023-01-30 15:07 UTC by jakubuid

2023-01-30 16:25 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> -                )
Removing it drastically will cause compatibility issues. Are we fine with that?

2023-01-30 16:27 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/common/NamespaceVO.kt
> +    //todo: change name to required namespaces and optional namespaces
Was this overlook or is this for upcoming work?

2023-01-30 16:27 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/common/NamespaceVO.kt
> +//        val chains: List<String>,
Why are chains removed?

2023-01-30 16:29 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/StorageModule.kt
> -        ),
Will migrations and db declarations be parts of next PR?

2023-01-30 16:30 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/StorageModule.kt
> -        ),
Nvm, now I see them below. Then we are missing migration

2023-01-30 16:31 UTC, Elyniss requested changes
Missing migrations

2023-01-31 03:12 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//            .all { extAccount -> extAccount.isNotEmpty() }
remove this if it's really not needed

2023-01-31 03:40 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +            namespace.methods.map { method -> method to namespace.chains }.toMutableList()
you don't need the `toMutableList()` anymore

2023-01-31 03:40 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +            namespace.methods.map { method -> method to namespace.accounts.map { getChainFromAccount(it) } }.toMutableList()
you don't need the `toMutableList()` anymore

2023-01-31 03:41 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//            .all { extChain -> extChain.isNotEmpty() }
let's remove this

2023-01-31 03:41 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//                onError(ValidationError.UserRejectedChains(NAMESPACE_EXTENSION_ACCOUNTS_MISSING_MESSAGE))
remove this

2023-01-31 03:41 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//            !areExtensionChainsNotEmpty(namespaces) -> onError(ValidationError.UnsupportedChains(NAMESPACE_EXTENSION_CHAINS_MISSING_MESSAGE))
remove this

2023-01-31 03:41 UTC, TalhaAli00 commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignEngine.kt
> +                Topic(topic), irnParams, sessionUpdate,
let's put all of these on separate lines

2023-01-31 04:05 UTC, TalhaAli00 commented on samples/web3wallet/src/main/kotlin/com/walletconnect/web3/wallet/ui/common/Namespaces.kt
> +        .onEach { (account, events) -> map[account] = (map[account] ?: emptyList()).plus(events) }
this can be simplified without having to do any mapping

```suggestion
return if (namespace.accounts.any { account -> account == accountId }) {
        namespace.events
    } else {
        emptyList()
    }
```

2023-01-31 04:07 UTC, TalhaAli00 commented on samples/web3wallet/src/main/kotlin/com/walletconnect/web3/wallet/ui/common/Namespaces.kt
> +        .onEach { (account, events) -> map[account] = (map[account] ?: emptyList()).plus(events) }
you could even do 

```suggestion
   return namespace.events.takeIf { namespace.accounts.contains(accountId) } ?: emptyList()
```

2023-01-31 04:09 UTC, TalhaAli00 reviewed
I also have concerns about this being a breaking change. Are we sure we don't want to just deprecate and create the new implementation separately?

2023-01-31 09:36 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/common/NamespaceVO.kt
> +    //todo: change name to required namespaces and optional namespaces
This is for upcoming work

2023-01-31 09:38 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/common/model/vo/clientsync/common/NamespaceVO.kt
> +//        val chains: List<String>,
Actually, it's not removed because the new caip-25 includes chains in the session namespaces. It's for upcoming work

2023-01-31 09:39 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/StorageModule.kt
> -        ),
The migrations are going to be added once the work for caip-25 is finished

2023-01-31 09:39 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//            .all { extAccount -> extAccount.isNotEmpty() }
I prefer to keep it until optional namespaces are added, it might me useful for the new validation

2023-01-31 09:40 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//            .all { extChain -> extChain.isNotEmpty() }
Same

2023-01-31 09:40 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//                onError(ValidationError.UserRejectedChains(NAMESPACE_EXTENSION_ACCOUNTS_MISSING_MESSAGE))
Same

2023-01-31 09:41 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/engine/domain/SignValidator.kt
> +//            !areExtensionChainsNotEmpty(namespaces) -> onError(ValidationError.UnsupportedChains(NAMESPACE_EXTENSION_CHAINS_MISSING_MESSAGE))
Same, this is only a part of a bigger task, those commented lines are going to be removed

2023-01-31 10:07 UTC, jakubuid commented
> I also have concerns about this being a breaking change. Are we sure we don't want to just deprecate and create the new implementation separately?

Regarding the breaking change issues. So I'm a bit divided here because having both implementations in parallel is going to create a lot of ambiguity in our code. Namespaces are used in almost every logic execution in the Sign SDK and the validation is different. We would have to distinguish between old and new caip-25 whenever we perform validation or database access.
It would look like having two internal implementations of the same SDK.

2023-01-31 10:15 UTC, jakubuid commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/client/Sign.kt
> -                )
See comment below

2023-01-31 10:39 UTC, Elyniss commented on sign/sdk/src/main/kotlin/com/walletconnect/sign/di/StorageModule.kt
> -        ),
Cool, we got checks on `develop` to catch that if we forget

2023-01-31 10:40 UTC, Elyniss approved these changes

2023-02-01 13:49 UTC, TalhaAli00 approved these changes

2023-02-01 14:03 UTC, merged