Added logic to save JSON RPC history to DB. Also made listeners in Wa…
WalletConnect/WalletConnectKotlinV2 pull request #65
Opened 2022-01-28 05:07 UTC by TalhaAli00

…lletConnectClient optional

2022-01-28 12:48 UTC, jakobuid requested changes

2022-01-28 12:48 UTC, jakobuid commented on walletconnectv2/src/main/kotlin/com/walletconnect/walletconnectv2/relay/domain/WalletConnectRelayer.kt
> +        jsonRpcHistory.setRequest(response.id, topic, null, serializedPayload)
I think here we should set the response for the request that we set in line 157.
In line 157 we set to DB a request that comes from another peer like eth_sign. So in `publishJsonRpcResponse` we should set our response to the request that comes from another peer.
Let's jump into quick call, so I can show you sth.

2022-01-29 16:29 UTC, TalhaAli00 commented on sample/src/main/java/com/walletconnect/sample/SampleApplication.kt
> +        const val PROJECT_ID = "2ee94aca5d98e6c05c38bce02bee952a" //TODO: register at https://walletconnect.com/register to get a project ID
moved TODO comments to where the init params are set

2022-02-01 07:57 UTC, jakobuid approved these changes

2022-02-02 04:26 UTC, merged