add generation of new JWT when old JWT is expired
WalletConnect/WalletConnectKotlinV2 pull request #672
Opened 2023-02-21 04:29 UTC by TalhaAli00

2023-02-21 08:26 UTC, jakubuid approved these changes

2023-02-21 08:31 UTC, jakubuid requested changes
The first relay url gets to be overridden with the new one with a new jwt, otherwise the new connection always is initialized with the expired jwt

2023-02-21 09:49 UTC, Elyniss commented on androidCore/sdk/src/main/kotlin/com/walletconnect/android/internal/common/di/CoreNetworkModule.kt
> +    single(named(AndroidCommonDITags.RELAY_URL)) {
Imo should be factory

2023-02-22 13:56 UTC, Elyniss approved these changes

2023-02-22 14:13 UTC, jakubuid approved these changes

2023-02-22 14:30 UTC, merged